/**
 * Stream Transformer
 *
 * Transforms SDK message streams into FlatStreamEventUnion for UI rendering.
 *
 * Responsibilities:
 * - Transform SDK stream_event messages to flat events for frontend
 * - Extract real session ID from system 'init' message
 * - Extract stats (cost, tokens, duration) from result messages
 *
 * NOTE: Does NOT store messages - SDK handles persistence natively.
 */

import { injectable, inject } from 'tsyringe';
import {
  SessionId,
  FlatStreamEventUnion,
  MessageTokenUsage,
  calculateMessageCost,
  getDiscoveredContextWindow,
  getModelContextWindow,
  AuthEnv,
  isDirectAnthropic,
} from '@ptah-extension/shared';
import { Logger, TOKENS } from '@ptah-extension/vscode-core';
import { SdkMessageTransformer } from '../sdk-message-transformer';
import { SDK_TOKENS } from '../di/tokens';
import { AUTH_PROVIDERS_TOKENS } from '@ptah-extension/auth-providers-tokens';
import {
  SDKMessage,
  isResultMessage,
  isSystemInit,
  isStreamEvent,
  isMessageStart,
  isMessageDelta,
  isCompactBoundary,
  isLocalCommandOutput,
  isTaskStarted,
  isTaskProgress,
  isTaskUpdated,
  isTaskNotification,
} from '../types/sdk-types/claude-sdk.types';
import type { IModelResolver } from '../auth-env.port';
import type { IPricingProvider } from '../pricing.port';
import type { NoActivityWatchdog } from './no-activity-watchdog';
import type { SessionMcpStatusCallbackRegistry } from './session-mcp-status-callback-registry';

/**
 * Callback type for notifying when real session ID is received from SDK.
 * - tabId: Frontend tab ID for direct routing (undefined for resumed sessions)
 * - realSessionId: The actual SDK UUID that should be used for all subsequent operations
 */
export type SessionIdResolvedCallback = (
  tabId: string | undefined,
  realSessionId: string,
) => void;

/**
 * The context window to publish for one model of a `result` message.
 *
 * Precedence, and the reason for each step:
 * 1. On a PROXY, a window provider discovery reported for this EXACT id. The
 *    CLI cannot know a non-Claude model's window and reports its generic
 *    200000 fallback, so the provider's own answer outranks it. Exact only —
 *    a fuzzy table match is not the provider answering (PR #493 review C).
 * 2. The SDK's own value, authoritative on direct Anthropic (`[1m]` and
 *    similar) and the best available on a proxy with nothing discovered.
 * 3. The general lookup (discovered → bundled table → Claude family regex),
 *    for the case where the SDK reported nothing at all.
 */
function resolveResultContextWindow(params: {
  readonly isDirect: boolean;
  readonly discoveredContextWindow: number;
  readonly sdkContextWindow: number;
  readonly knownContextWindow: number;
}): number {
  if (!params.isDirect && params.discoveredContextWindow > 0) {
    return params.discoveredContextWindow;
  }
  if (params.sdkContextWindow > 0) return params.sdkContextWindow;
  return params.knownContextWindow;
}

/**
 * Model usage data from SDK result message
 * Contains context window size for percentage calculation
 */
export interface ResultModelUsage {
  /** Model identifier (e.g., "claude-sonnet-4-20250514") */
  model: string;
  /** Input tokens used by this model (cumulative across all turns) */
  inputTokens: number;
  /** Output tokens generated by this model (cumulative across all turns) */
  outputTokens: number;
  /** Total context window size for this model */
  contextWindow: number;
  /** Per-model cost in USD from SDK */
  costUSD: number | null;
  /** Cache read input tokens for this model (cumulative across all turns) */
  cacheReadInputTokens: number;
  /**
   * Current context fill from the last API turn (input + cache_read +
   * cache_creation tokens). Unlike the cumulative
   * inputTokens/cacheReadInputTokens, this represents the actual prompt size
   * sent on the most recent turn — i.e., the real context window fill level.
   * Written from `message_start` usage and replaced by the final
   * `message_delta` usage when the delta carries input/cache numbers (proxied
   * providers send only synthetic zeros in `message_start` and the real
   * numbers in the delta). Excludes cumulative output. Undefined if no usage
   * was captured for the model.
   */
  lastTurnContextTokens?: number;
}

/**
 * Callback type for notifying when result message with stats is received
 * Uses MessageTokenUsage from shared for type consistency
 */
export type ResultStatsCallback = (stats: {
  sessionId: SessionId;
  cost: number | null;
  tokens: MessageTokenUsage;
  duration: number;
  /** Per-model usage data including context window size */
  modelUsage?: ResultModelUsage[];
}) => void;

/**
 * Configuration for stream transformation
 */
export interface StreamTransformConfig {
  sdkQuery: AsyncIterable<SDKMessage>;
  sessionId: SessionId;
  initialModel: string;
  onSessionIdResolved?: SessionIdResolvedCallback;
  onResultStats?: ResultStatsCallback;
  /**
   * Fired on the SDK `result` message — the turn boundary — BEFORE any stats
   * work. Deliberately separate from `onResultStats`, which is skipped when
   * `validateStats` rejects a malformed payload and which awaits a pricing
   * lookup first. The streaming pump's turn claim must be released on every
   * result, promptly and unconditionally, or a message held mid-turn waits for
   * the 180s no-activity watchdog instead of the turn (TASK_2026_294).
   */
  onTurnEnd?: () => void;
  /**
   * Passed to callback so frontend can find tab directly without temp ID lookup.
   */
  tabId?: string;
  /**
   * No-stream-activity watchdog for the underlying SDK query. When present, the
   * transformer `start()`s it before consuming the stream, `kick()`s it on
   * every SDK message (any event — message, partial/streaming delta, tool_use,
   * tool_result, thinking — resets the inactivity window), and `stop()`s it in
   * the `finally` so it can neither leak nor fire after the turn ends. On
   * timeout the watchdog resolves pending permissions and aborts the query with
   * a descriptive error, so a genuinely stuck session surfaces instead of
   * hanging forever; a long-but-alive turn keeps kicking it and never trips it.
   */
  activityWatchdog?: NoActivityWatchdog;
}

/**
 * Validated stats interface
 * Uses MessageTokenUsage from shared for type consistency
 */
interface ValidatedStats {
  sessionId: SessionId;
  cost: number | null;
  tokens: MessageTokenUsage;
  duration: number;
  /** Per-model usage data including context window size */
  modelUsage?: ResultModelUsage[];
}

/**
 * Validate stats from SDK result message
 * Ensures all numeric values are within expected bounds to catch SDK bugs
 *
 * @param stats - Raw stats extracted from SDK result message
 * @param logger - Logger instance for validation warnings
 * @returns Validated stats or null if validation fails
 */
function validateStats(
  stats: {
    sessionId: SessionId;
    cost: number | null;
    tokens: { input: number; output: number };
    duration: number;
    modelUsage?: ResultModelUsage[];
  },
  logger: Logger,
): ValidatedStats | null {
  if (
    stats.cost !== null &&
    (stats.cost < 0 ||
      stats.cost > 100 ||
      isNaN(stats.cost) ||
      !isFinite(stats.cost))
  ) {
    logger.warn('[StreamTransformer] Invalid cost value from SDK:', {
      cost: stats.cost,
      sessionId: stats.sessionId,
    });
    return null;
  }
  if (
    stats.tokens.input < 0 ||
    stats.tokens.input > 1000000 ||
    isNaN(stats.tokens.input) ||
    !isFinite(stats.tokens.input) ||
    stats.tokens.output < 0 ||
    stats.tokens.output > 1000000 ||
    isNaN(stats.tokens.output) ||
    !isFinite(stats.tokens.output)
  ) {
    logger.warn('[StreamTransformer] Invalid token values from SDK:', {
      tokens: stats.tokens,
      sessionId: stats.sessionId,
    });
    return null;
  }
  if (
    stats.duration < 0 ||
    stats.duration > 3600000 ||
    isNaN(stats.duration) ||
    !isFinite(stats.duration)
  ) {
    logger.warn('[StreamTransformer] Invalid duration value from SDK:', {
      duration: stats.duration,
      sessionId: stats.sessionId,
    });
    return null;
  }

  return stats; // All validations passed
}

/**
 * StreamTransformer - Transforms SDK messages to flat stream events
 *
 * Responsibilities:
 * - Transform SDK stream_event messages to FlatStreamEventUnion
 * - Extract real session ID from system 'init' message
 * - Extract stats (cost, tokens, duration) from result messages
 * - Handle authentication errors gracefully
 *
 * Does NOT store messages - SDK handles persistence natively.
 */
@injectable()
export class StreamTransformer {
  constructor(
    @inject(TOKENS.LOGGER) private readonly logger: Logger,
    @inject(SDK_TOKENS.SDK_MESSAGE_TRANSFORMER)
    private readonly messageTransformer: SdkMessageTransformer,
    @inject(AUTH_PROVIDERS_TOKENS.SDK_AUTH_ENV)
    private readonly authEnv: AuthEnv,
    @inject(AUTH_PROVIDERS_TOKENS.SDK_MODEL_RESOLVER)
    private readonly modelResolver: IModelResolver,
    @inject(SDK_TOKENS.PRICING_PROVIDER)
    private readonly pricingProvider: IPricingProvider,
    /**
     * Fan-out for what the CLI reported about this session's MCP servers.
     *
     * NOT a `StreamTransformConfig` callback, because the other producer of the
     * same signal — the CLI stderr notice in `SdkQueryOptionsBuilder` — is on
     * the other side of the session-start path and shares no config object with
     * this one. See the registry's own file header.
     */
    @inject(SDK_TOKENS.SDK_SESSION_MCP_STATUS_CALLBACK_REGISTRY)
    private readonly mcpStatus: SessionMcpStatusCallbackRegistry,
  ) {}

  /**
   * Create a transformed flat event stream from SDK messages
   */
  transform(
    config: StreamTransformConfig,
  ): AsyncIterable<FlatStreamEventUnion> {
    const {
      sdkQuery,
      sessionId,
      initialModel,
      onSessionIdResolved,
      onResultStats,
      onTurnEnd,
      tabId,
      activityWatchdog,
    } = config;
    const logger = this.logger;
    // ONE transformer per stream, never the DI singleton (TASK_2026_370).
    //
    // `SdkMessageTransformer` keys its streaming bookkeeping on
    // `parent_tool_use_id || ''` — a context, with no session dimension — and is
    // registered `Lifecycle.Singleton`. Every root assistant turn of every
    // session therefore wrote the same `''` slot: with two chat sessions live,
    // session A's `content_block_start` resolved to session B's message id (so
    // A's text landed on B's bubble), `onMessageDelta` attributed A's token
    // usage to B's message, and a compact boundary in either session called
    // `clearStreamingState()` on the maps of BOTH.
    //
    // `createIsolated()` is the mechanism that already existed for exactly this;
    // `HarnessStreamBroadcaster` and the Ptah-CLI stream loop each take one per
    // stream, and the interactive chat path was the one caller that did not.
    // `transform()` is called once per session stream, so this is the per-stream
    // seam. The shared collaborators (`usageTracker`, `turnState`,
    // `sessionLifecycle`) are passed through by `createIsolated` and stay
    // shared — they are keyed by session id already.
    const messageTransformer = this.messageTransformer.createIsolated();
    const authEnv = this.authEnv;
    const modelResolver = this.modelResolver;
    const pricingProvider = this.pricingProvider;
    const mcpStatus = this.mcpStatus;

    return {
      async *[Symbol.asyncIterator]() {
        let sdkMessageCount = 0;
        let yieldedEventCount = 0;
        let effectiveSessionId = sessionId;
        // Per-component last-turn context, keyed by model. message_start
        // REPLACES all three components; the final message_delta REPLACES only
        // the components it carries (`??` skips null/undefined only, so an
        // explicit 0 is a real reading and an absent field keeps the last
        // known value). Components are stored separately so an output-only
        // delta — the direct Anthropic shape — cannot zero input/cache.
        const lastTurnContextByModel = new Map<
          string,
          { input: number; cacheRead: number; cacheCreation: number }
        >();
        // message_delta carries no model, so the tracker remembers the model
        // of the message_start it belongs to.
        let currentStreamModel: string | null = null;
        let loggedEagerMcpTools = false;

        // Arm the no-activity watchdog before consuming the stream. It fires
        // only if NO SDK message arrives for the full inactivity window; every
        // message below kicks it, so a slow-but-alive turn never trips it.
        activityWatchdog?.start();

        try {
          for await (const sdkMessage of sdkQuery) {
            // Any stream activity — message, partial/streaming delta, tool_use,
            // tool_result, thinking — resets the inactivity window.
            activityWatchdog?.observe(sdkMessage);
            sdkMessageCount++;

            if (isStreamEvent(sdkMessage)) {
              const event = sdkMessage.event;
              if (isMessageStart(event)) {
                const model = event.message.model;
                const turnUsage = event.message.usage;
                currentStreamModel = model ?? null;
                if (model && turnUsage) {
                  lastTurnContextByModel.set(model, {
                    input: turnUsage.input_tokens ?? 0,
                    cacheRead: turnUsage.cache_read_input_tokens ?? 0,
                    cacheCreation: turnUsage.cache_creation_input_tokens ?? 0,
                  });
                }
              } else if (isMessageDelta(event)) {
                // Proxied providers (Codex/OpenRouter via the responses
                // translation proxy) emit message_start with synthetic zero
                // usage and the real input/cache numbers ONLY in the final
                // message_delta. Read them here so the context gauge tracks
                // the real prompt size. `MessageDeltaEvent.usage` is typed
                // output-only because direct Anthropic deltas normally are,
                // so read the optional input/cache fields through the same
                // widened structural cast as
                // stream-event.transformer's onMessageDelta.
                const model = currentStreamModel;
                const previous = model
                  ? lastTurnContextByModel.get(model)
                  : undefined;
                const usage = (
                  event as {
                    usage?: {
                      input_tokens?: number;
                      cache_read_input_tokens?: number;
                      cache_creation_input_tokens?: number;
                    };
                  }
                ).usage;
                if (model && previous && usage) {
                  lastTurnContextByModel.set(model, {
                    input: usage.input_tokens ?? previous.input,
                    cacheRead: usage.cache_read_input_tokens ?? previous.cacheRead,
                    cacheCreation:
                      usage.cache_creation_input_tokens ??
                      previous.cacheCreation,
                  });
                }
              }
            }
            if (isSystemInit(sdkMessage)) {
              const realSessionId = sdkMessage.session_id;
              effectiveSessionId = realSessionId as SessionId;
              if (onSessionIdResolved) {
                onSessionIdResolved(tabId, realSessionId);
              }
              if (!loggedEagerMcpTools) {
                loggedEagerMcpTools = true;
                const eagerPtahTools = sdkMessage.tools.filter((name) =>
                  name.startsWith('mcp__ptah'),
                );
                logger.debug(
                  `[StreamTransformer] Eager-loaded ptah MCP tools (${eagerPtahTools.length})`,
                  {
                    sessionId: realSessionId,
                    eagerPtahTools,
                    eagerPtahToolCount: eagerPtahTools.length,
                    mcpServers: sdkMessage.mcp_servers,
                  },
                );
              }
              // Publish the same `mcp_servers` the log above prints. Before
              // TASK_2026_375 this was the ONLY place it went: a Smithery
              // server the CLI itself reported as `needs-auth` was logged at
              // debug level and the UI showed it as installed and working.
              //
              // This is not turn state — it lands once per session, at init,
              // and no chunk depends on it — so the direct channel is correct
              // here in a way it is not for `turn_state`. See the registry's
              // file header.
              if (Array.isArray(sdkMessage.mcp_servers)) {
                mcpStatus.notifyAll({
                  kind: 'servers',
                  sessionId: realSessionId,
                  servers: sdkMessage.mcp_servers.map((server) => ({
                    name: server.name,
                    status: server.status,
                  })),
                });
              }
            }
            if (isResultMessage(sdkMessage)) {
              // Turn boundary first — see `onTurnEnd`'s contract. Nothing below
              // may gate it.
              onTurnEnd?.();
              if (!onResultStats) {
                logger.error(
                  '[StreamTransformer] Result stats callback not set - stats will be lost!',
                  { sessionId: effectiveSessionId },
                );
              } else {
                const isDirect = isDirectAnthropic(authEnv);
                const modelUsageList: ResultModelUsage[] = [];
                if (sdkMessage.modelUsage) {
                  for (const [model, usage] of Object.entries(
                    sdkMessage.modelUsage,
                  )) {
                    if (model.startsWith('<') && model.endsWith('>')) {
                      continue;
                    }
                    const priced = modelResolver.resolveForCost(model, authEnv);
                    const resolvedModel = priced.modelId;
                    let costUSD: number | null;
                    if (isDirect) {
                      costUSD = usage.costUSD;
                    } else {
                      // Prefer the already-hydrated map; only pay for a catalog
                      // round-trip when the model is genuinely unknown to it.
                      const pricing =
                        priced.pricing ??
                        (await pricingProvider.getPricing(resolvedModel));
                      costUSD = pricing
                        ? calculateMessageCost(
                            resolvedModel,
                            {
                              input: usage.inputTokens,
                              output: usage.outputTokens,
                              cacheHit: usage.cacheReadInputTokens ?? 0,
                              cacheCreation:
                                usage.cacheCreationInputTokens ?? 0,
                            },
                            pricing,
                          )
                        : null;
                    }
                    const knownContextWindow =
                      getModelContextWindow(resolvedModel);
                    const trackedContext = lastTurnContextByModel.get(model);
                    // On a proxy the CLI cannot know a non-Claude model's
                    // window and reports its generic 200000 fallback, so a
                    // window the PROVIDER ITSELF reported for this exact id
                    // wins there. It must be the EXACT discovered value, never
                    // `getModelContextWindow`: that falls through to the
                    // bundled pricing table's partial matching, so an
                    // undiscovered `gpt-4o-ultra` resolved to `gpt-4o`'s
                    // 128000 and overrode the SDK for a model nobody
                    // registered (PR #493 review C). Direct Anthropic keeps
                    // the SDK value, authoritative for `[1m]` and similar.
                    const discoveredContextWindow =
                      getDiscoveredContextWindow(resolvedModel);
                    const contextWindow = resolveResultContextWindow({
                      isDirect,
                      discoveredContextWindow,
                      sdkContextWindow: usage.contextWindow,
                      knownContextWindow,
                    });
                    modelUsageList.push({
                      model: resolvedModel,
                      inputTokens: usage.inputTokens,
                      outputTokens: usage.outputTokens,
                      contextWindow,
                      costUSD,
                      cacheReadInputTokens: usage.cacheReadInputTokens ?? 0,
                      lastTurnContextTokens: trackedContext
                        ? trackedContext.input +
                          trackedContext.cacheRead +
                          trackedContext.cacheCreation
                        : undefined,
                    });
                  }
                  if (modelUsageList.length > 1) {
                    modelUsageList.sort((a, b) => {
                      if (initialModel) {
                        const normalizedInit = initialModel.toLowerCase();
                        const aFuzzy =
                          a.model === initialModel ||
                          a.model.toLowerCase().includes(normalizedInit) ||
                          normalizedInit.includes(a.model.toLowerCase())
                            ? 1
                            : 0;
                        const bFuzzy =
                          b.model === initialModel ||
                          b.model.toLowerCase().includes(normalizedInit) ||
                          normalizedInit.includes(b.model.toLowerCase())
                            ? 1
                            : 0;
                        if (aFuzzy !== bFuzzy) return bFuzzy - aFuzzy;
                      }
                      return b.outputTokens - a.outputTokens;
                    });
                  }
                }
                let totalCost: number | null;
                if (isDirect) {
                  totalCost = sdkMessage.total_cost_usd;
                } else if (modelUsageList.some((m) => m.costUSD !== null)) {
                  totalCost = modelUsageList.reduce(
                    (sum, m) => sum + (m.costUSD ?? 0),
                    0,
                  );
                } else {
                  totalCost = null;
                }

                const rawStats = {
                  sessionId: effectiveSessionId,
                  cost: totalCost,
                  tokens: {
                    input: sdkMessage.usage.input_tokens,
                    output: sdkMessage.usage.output_tokens,
                    cacheRead: sdkMessage.usage.cache_read_input_tokens ?? 0,
                    cacheCreation:
                      sdkMessage.usage.cache_creation_input_tokens ?? 0,
                  },
                  duration: sdkMessage.duration_ms,
                  modelUsage:
                    modelUsageList.length > 0 ? modelUsageList : undefined,
                };
                const validatedStats = validateStats(rawStats, logger);
                if (validatedStats) {
                  onResultStats(validatedStats);
                }
              }
            }
            if (isCompactBoundary(sdkMessage)) {
              lastTurnContextByModel.clear();
            }

            if (
              sdkMessage.type === 'stream_event' ||
              sdkMessage.type === 'assistant' ||
              sdkMessage.type === 'user' ||
              // The result's `turn_state` must travel IN the stream, after the
              // last chunk of the turn it closes (TASK_2026_360).
              isResultMessage(sdkMessage) ||
              isCompactBoundary(sdkMessage) ||
              isLocalCommandOutput(sdkMessage) ||
              isTaskStarted(sdkMessage) ||
              isTaskProgress(sdkMessage) ||
              isTaskUpdated(sdkMessage) ||
              isTaskNotification(sdkMessage)
            ) {
              const flatEvents = messageTransformer.transform(
                sdkMessage,
                effectiveSessionId,
              );

              for (const event of flatEvents) {
                yieldedEventCount++;

                yield event;
              }
            }
          }

          logger.debug(
            `[StreamTransformer] Stream ended for ${sessionId}: ${sdkMessageCount} SDK messages, ${yieldedEventCount} events yielded`,
          );
        } catch (error) {
          const errorObj =
            error instanceof Error ? error : new Error(String(error));
          const lowerMessage = errorObj.message.toLowerCase();
          const isUserAbort =
            lowerMessage.includes('aborted by user') ||
            lowerMessage.includes('abort') ||
            lowerMessage.includes('cancelled') ||
            lowerMessage.includes('canceled');

          if (isUserAbort) {
            logger.debug(
              `[StreamTransformer] Session ${sessionId} aborted by user`,
            );
          } else {
            logger.error(
              `[StreamTransformer] Session ${sessionId} error: ${errorObj.message}`,
              errorObj,
            );
            const isAuthError =
              errorObj.message.includes('401') ||
              lowerMessage.includes('unauthorized') ||
              lowerMessage.includes('authentication failed') ||
              lowerMessage.includes('invalid api key') ||
              lowerMessage.includes('invalid token') ||
              lowerMessage.includes('api_key');

            if (isAuthError) {
              logger.error('[StreamTransformer] AUTHENTICATION ERROR!');
              logger.error(
                '[StreamTransformer] SDK requires valid API key from console.anthropic.com',
              );
              logger.error(
                `[StreamTransformer] Current: ANTHROPIC_API_KEY=${
                  authEnv.ANTHROPIC_API_KEY
                    ? `SET (${authEnv.ANTHROPIC_API_KEY.substring(0, 10)}...)`
                    : 'NOT SET'
                }`,
              );
            }
          }

          throw error;
        } finally {
          // Stop the watchdog on every teardown path (end-of-stream, error,
          // abort) so it can neither leak nor fire after the turn ends.
          activityWatchdog?.stop();
          logger.debug(`[StreamTransformer] Session ${sessionId} stream ended`);
        }
      },
    };
  }
}
