/**
 * Persistence RPC Handlers.
 *
 * Surfaces two `db:*` maintenance methods backed by
 * `@ptah-extension/persistence-sqlite`:
 *
 *   - db:health  → inspect connection state, pragma stats, WAL size
 *   - db:reset   → backup → close → rename old file → reopen (5-step workflow)
 *
 * Both methods are license-exempt (maintenance / recovery surfaces) and
 * Electron-only (better-sqlite3 does not run in the VS Code extension host).
 *
 * Per architecture §7 the `db:health` handler MUST NOT throw — it always
 * returns a structured result even when the connection is unavailable.
 * Per architecture §8 the `db:reset` handler may throw `RpcUserError` for
 * user-recoverable guard conditions (wrong confirm token, write in progress).
 */

import { injectable, inject } from 'tsyringe';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { TOKENS } from '@ptah-extension/vscode-core';
import { RpcUserError } from '@ptah-extension/vscode-core';
import type { Logger, RpcHandler } from '@ptah-extension/vscode-core';
import {
  PERSISTENCE_TOKENS,
  SqliteConnectionService,
} from '@ptah-extension/persistence-sqlite';
import type { IBackupService } from '@ptah-extension/persistence-sqlite';
import type {
  RpcMethodName,
  DbHealthResult,
  DbResetResult,
} from '@ptah-extension/shared';

// Re-exported so consumers that import from this handler module still compile.
export type { DbHealthResult, DbResetResult } from '@ptah-extension/shared';

/** Optional request params for `db:health`. */
export interface DbHealthParams {
  /** When true, runs the slow PRAGMA integrity_check in addition to quick_check. */
  fullCheck?: boolean;
}

/**
 * Request params for `db:reset`.
 *
 * F-M1 security fix: the static `'CONFIRM'` string was bypassable by any RPC
 * caller (including a compromised agent). The confirmation flow now uses a
 * per-invocation challenge token (UUID) generated by the trusted main-process
 * menu handler via `mintResetChallengeToken()`. The UUID is valid for 60 s and
 * is consumed on first use (single-use). Agents that construct RPC calls
 * directly cannot mint new tokens — they only see the opaque string passed
 * through the renderer, which is never exposed on `window.ptah`.
 *
 * The static `'CONFIRM'` fallback is retained for callers that have not yet
 * been migrated (backwards-compat grace period) but is documented as DEPRECATED.
 */
export interface DbResetParams {
  /**
   * A challenge token obtained from `mintResetChallengeToken()` (preferred), or
   * the static literal `'CONFIRM'` (deprecated — use challenge tokens instead).
   */
  confirm: string;
}

// ---- Handler class ---------------------------------------------------------

/**
 * Challenge token registry for the db:reset confirmation flow (F-M1).
 *
 * Tokens are generated by `mintResetChallengeToken()` in the trusted
 * main-process context (Electron menu handler) and are valid for 60 s.
 * Each token is single-use — it is deleted on first successful validation.
 * Agents that construct RPC calls directly cannot mint tokens.
 */
const CHALLENGE_TTL_MS = 60_000;
const pendingChallenges = new Map<string, number>(); // token → expiry (epoch ms)

/**
 * Mint a single-use challenge token for the db:reset flow.
 * Call this from the trusted main-process context (e.g. the Electron menu)
 * BEFORE dispatching the IPC to the renderer. Pass the returned token as
 * `params.confirm` in the `db:reset` RPC call.
 *
 * @returns A UUID-format challenge token valid for 60 s.
 */
export function mintResetChallengeToken(): string {
  // Purge expired tokens to prevent unbounded memory growth.
  const now = Date.now();
  for (const [token, expiry] of pendingChallenges) {
    if (now >= expiry) pendingChallenges.delete(token);
  }
  const token = crypto.randomUUID();
  pendingChallenges.set(token, now + CHALLENGE_TTL_MS);
  return token;
}

@injectable()
export class PersistenceRpcHandlers {
  static readonly METHODS = [
    'db:health',
    'db:reset',
  ] as const satisfies readonly RpcMethodName[];

  constructor(
    @inject(TOKENS.LOGGER) private readonly logger: Logger,
    @inject(TOKENS.RPC_HANDLER) private readonly rpcHandler: RpcHandler,
    @inject(PERSISTENCE_TOKENS.SQLITE_CONNECTION)
    private readonly connection: SqliteConnectionService,
    @inject(PERSISTENCE_TOKENS.BACKUP_SERVICE)
    private readonly backup: IBackupService,
  ) {}

  /** Register both `db:*` methods with the shared RpcHandler. */
  register(): void {
    this.rpcHandler.registerMethod<DbHealthParams, DbHealthResult>(
      'db:health',
      (params) => this.handleHealth(params),
    );

    this.rpcHandler.registerMethod<DbResetParams, DbResetResult>(
      'db:reset',
      (params) => this.handleReset(params),
    );

    this.logger.info('[persistence] RPC handlers registered');
  }

  // ---- db:health -----------------------------------------------------------

  /**
   * Return a structured snapshot of the SQLite connection's health.
   * Never throws — returns `{ isOpen: false }` with nulls when unavailable.
   */
  private async handleHealth(
    params: DbHealthParams | undefined,
  ): Promise<DbHealthResult> {
    const fullCheck = params?.fullCheck === true;

    // When the connection is offline return a minimal result so the UI can
    // render the "persistence offline" badge without further network calls.
    if (this.connection.unavailable !== null) {
      return {
        isOpen: false,
        quickCheckPassed: null,
        foreignKeyViolations: null,
        foreignKeyViolationSample: [],
        dbSizeMb: null,
        freelistRatio: null,
        walSizeKb: null,
        vecExtensionLoaded: false,
        lastMigrationVersion: 0,
        fullCheckRun: false,
        integrityCheckPassed: null,
      };
    }

    const result: DbHealthResult = {
      isOpen: true,
      quickCheckPassed: null,
      foreignKeyViolations: null,
      foreignKeyViolationSample: [],
      dbSizeMb: null,
      freelistRatio: null,
      walSizeKb: null,
      vecExtensionLoaded: this.connection.vecExtensionLoaded,
      lastMigrationVersion: this.connection.lastMigrationVersion,
      fullCheckRun: fullCheck,
      integrityCheckPassed: null,
    };

    try {
      const db = this.connection.db;

      // quick_check
      try {
        const qc = db.pragma('quick_check', { simple: true }) as string;
        result.quickCheckPassed = qc === 'ok';
      } catch (err: unknown) {
        this.logger.warn('[persistence] db:health quick_check failed', {
          error: err instanceof Error ? err.message : String(err),
        });
      }

      // foreign_key_check
      try {
        const rows = db.pragma('foreign_key_check') as Array<{
          table: string;
          rowid: number;
          parent: string;
          fkid: number;
        }>;
        result.foreignKeyViolations = rows.length;
        result.foreignKeyViolationSample = rows.slice(0, 3);
      } catch (err: unknown) {
        this.logger.warn('[persistence] db:health foreign_key_check failed', {
          error: err instanceof Error ? err.message : String(err),
        });
      }

      // Page / size stats
      try {
        const pageCount = db.pragma('page_count', { simple: true }) as number;
        const pageSize = db.pragma('page_size', { simple: true }) as number;
        const freelist = db.pragma('freelist_count', {
          simple: true,
        }) as number;
        result.dbSizeMb =
          Math.round(((pageCount * pageSize) / (1024 * 1024)) * 100) / 100;
        result.freelistRatio =
          pageCount > 0
            ? Math.round((freelist / pageCount) * 10000) / 10000
            : 0;
      } catch (err: unknown) {
        this.logger.warn('[persistence] db:health page stats failed', {
          error: err instanceof Error ? err.message : String(err),
        });
      }

      // WAL file size — read from fs, not from PRAGMA (PRAGMA wal_checkpoint
      // would mutate state; we only want to observe)
      try {
        const walPath = this.connection.dbPath + '-wal';
        const walStat = fs.statSync(walPath);
        result.walSizeKb = Math.round(walStat.size / 1024);
      } catch {
        // WAL file absent = fully checkpointed = effectively 0 bytes
        result.walSizeKb = null;
      }

      // Optional slow integrity_check
      if (fullCheck) {
        try {
          const ic = db.pragma('integrity_check', { simple: true }) as string;
          result.integrityCheckPassed = ic === 'ok';
        } catch (err: unknown) {
          this.logger.warn('[persistence] db:health integrity_check failed', {
            error: err instanceof Error ? err.message : String(err),
          });
          result.integrityCheckPassed = false;
        }
      }
    } catch (err: unknown) {
      // db getter can throw RpcUserError when connection closed between the
      // unavailable check above and now (race). Return the offline shape.
      this.logger.warn('[persistence] db:health lost connection during check', {
        error: err instanceof Error ? err.message : String(err),
      });
      return {
        isOpen: false,
        quickCheckPassed: null,
        foreignKeyViolations: null,
        foreignKeyViolationSample: [],
        dbSizeMb: null,
        freelistRatio: null,
        walSizeKb: null,
        vecExtensionLoaded: false,
        lastMigrationVersion: 0,
        fullCheckRun: false,
        integrityCheckPassed: null,
      };
    }

    return result;
  }

  // ---- db:reset ------------------------------------------------------------

  /**
   * 5-step reset workflow:
   *  1. backup('reset')
   *  2. connection.close()
   *  3. fs.renameSync (EPERM async retry after 200 ms on Windows)
   *     Also renames -wal and -shm sidecar files.
   *  4. connection.openAndMigrate()
   *  5. Return success result
   *
   * Throws `RpcUserError('PERSISTENCE_UNAVAILABLE')` for user-recoverable
   * guard failures (wrong confirm token, write in flight). Other failures
   * are caught and returned as `{ success: false }`.
   *
   * Security notes:
   *  - The confirmation token must be a UUID minted by `mintResetChallengeToken()`
   *    in the trusted main-process context. The static `'CONFIRM'` literal is
   *    retained for the deprecated fallback path only.
   *  - The returned `backupPath` contains only the basename of the backup
   *    file — never the absolute path — to avoid leaking the OS username via RPC.
   *    Error messages are sanitised (absolute paths stripped) before being returned.
   */
  private async handleReset(
    params: DbResetParams | undefined,
  ): Promise<DbResetResult> {
    // Guard: validate the confirmation token.
    // Accept a valid single-use challenge UUID (preferred) OR the deprecated
    // static 'CONFIRM' literal. The challenge UUID cannot be minted by renderer-
    // side agents, closing the agent-bypass path described in the security review.
    if (!params || !this.isValidResetConfirmation(params.confirm)) {
      throw new RpcUserError(
        'Reset requires a valid confirmation token',
        'PERSISTENCE_UNAVAILABLE',
      );
    }

    // Best-effort guard: reject while a write transaction is open
    if (this.connection.isOpen) {
      try {
        const db = this.connection.db;
        if (db.inTransaction) {
          throw new RpcUserError(
            'A write is in progress. Please try again in a moment.',
            'PERSISTENCE_UNAVAILABLE',
          );
        }
      } catch (err: unknown) {
        if (err instanceof RpcUserError) throw err;
        // Connection went offline between isOpen check and db getter — proceed
        // with reset since there cannot be an in-flight transaction.
      }
    }

    const dbPath = this.connection.dbPath;
    let rawBackupPath: string | null = null;

    try {
      // Step 1: backup
      if (this.connection.isOpen) {
        try {
          rawBackupPath = await this.backup.backup(this.connection.db, 'reset');
        } catch (err: unknown) {
          // backup() should never throw, but be defensive
          this.logger.warn('[persistence] db:reset backup error (non-fatal)', {
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }

      // Step 2: close (WAL checkpoint + close)
      this.connection.close();

      // Step 3: rename old file to .deleted-<ts>-<random>.
      // Include a random hex suffix to avoid collision under rapid resets
      // (Date.now() has ms resolution; two resets in the same ms would collide).
      // Also rename -wal and -shm sidecar files so SQLite cannot replay
      // stale WAL content into the freshly-opened empty DB.
      const randomSuffix = crypto.randomBytes(4).toString('hex');
      const deletedPath = `${dbPath}.deleted-${Date.now()}-${randomSuffix}`;
      const renamed = await this.tryRename(dbPath, deletedPath);
      if (!renamed.ok) {
        return {
          backupPath: rawBackupPath ? path.basename(rawBackupPath) : null,
          success: false,
          message: 'Could not rename old database file.',
        };
      }

      // Clean up WAL and SHM sidecars — non-fatal if absent or locked.
      this.renameDbSidecar(`${dbPath}-wal`, `${deletedPath}-wal`);
      this.renameDbSidecar(`${dbPath}-shm`, `${deletedPath}-shm`);

      // Step 4: open fresh DB + run migrations
      await this.connection.openAndMigrate();

      // Step 5: return success.
      // Return only the basename of the backup path to avoid leaking
      // the OS username (C:\Users\<name>\... or /home/<user>/...) to the renderer.
      const backupBasename = rawBackupPath
        ? path.basename(rawBackupPath)
        : null;
      const backupNote = backupBasename
        ? `Backup: ${backupBasename}`
        : 'No backup was taken.';
      return {
        backupPath: backupBasename,
        success: true,
        message: `Database reset. ${backupNote}`,
      };
    } catch (err: unknown) {
      // Sanitise error messages — strip absolute paths before returning
      // to the renderer so OS usernames are not leaked.
      const raw = err instanceof Error ? err.message : String(err);
      const sanitised = sanitiseErrorMessage(raw);
      this.logger.error('[persistence] db:reset failed', { error: raw });
      return {
        backupPath: rawBackupPath ? path.basename(rawBackupPath) : null,
        success: false,
        message: `Reset failed: ${sanitised}`,
      };
    }
  }

  /**
   * Validate the reset confirmation token.
   * Accepts either a single-use UUID challenge token (preferred) or the
   * deprecated static literal 'CONFIRM'.
   */
  private isValidResetConfirmation(token: string): boolean {
    // Check the challenge token registry first (preferred path).
    const expiry = pendingChallenges.get(token);
    if (expiry !== undefined) {
      pendingChallenges.delete(token); // single-use
      return Date.now() < expiry;
    }
    // Deprecated fallback: static literal for callers not yet migrated.
    return token === 'CONFIRM';
  }

  /**
   * Attempt `fs.renameSync`. On EPERM (antivirus interference on Windows),
   * waits 200 ms (async, non-blocking) and retries once.
   * Returns `{ ok: true }` on success or `{ ok: false, error: string }` after
   * both attempts fail.
   *
   * Uses async `setTimeout` (not a sync busy-wait spin-loop) so the Electron
   * main-process event loop is not blocked during the 200 ms wait.
   */
  private async tryRename(
    src: string,
    dest: string,
  ): Promise<{ ok: true } | { ok: false; error: string }> {
    const attempt = ():
      | { ok: true; error?: undefined }
      | { ok: false; error: string } => {
      try {
        fs.renameSync(src, dest);
        return { ok: true };
      } catch (err: unknown) {
        return {
          ok: false,
          error: err instanceof Error ? err.message : String(err),
        };
      }
    };

    const first = attempt();
    if (first.ok) return { ok: true };

    // Only retry on EPERM (Windows AV interference)
    if (!first.error.includes('EPERM')) return first;

    // Async 200 ms wait so the event loop is not blocked while Windows AV
    // releases its handle on the file.
    await new Promise<void>((resolve) => setTimeout(resolve, 200));

    return attempt();
  }

  /**
   * Rename a WAL or SHM sidecar file as part of the db:reset flow.
   * Non-fatal — if the file is absent (fully checkpointed) or cannot be
   * renamed, logs a debug message and continues.
   */
  private renameDbSidecar(src: string, dest: string): void {
    try {
      if (fs.existsSync(src)) {
        fs.renameSync(src, dest);
        this.logger.debug('[persistence] db:reset renamed sidecar', {
          src: path.basename(src),
          dest: path.basename(dest),
        });
      }
    } catch (err: unknown) {
      // Non-fatal: a failed sidecar rename is logged but must not abort the reset.
      this.logger.warn(
        '[persistence] db:reset sidecar rename failed (non-fatal)',
        {
          file: path.basename(src),
          error: err instanceof Error ? err.message : String(err),
        },
      );
    }
  }
}

/**
 * F-M3: Strip absolute filesystem paths from error messages before returning
 * them to the renderer. Matches common OS path patterns:
 *  - POSIX:   /home/user/... or /Users/user/...
 *  - Windows: C:\Users\user\... or C:/Users/user/...
 *
 * Replaced with a generic '[path redacted]' placeholder.
 */
function sanitiseErrorMessage(message: string): string {
  return message
    .replace(/[A-Za-z]:[/\\][^\s,'"]+/g, '[path redacted]')
    .replace(/\/(?:home|Users|root)\/[^\s,'"]+/g, '[path redacted]');
}
