#!/usr/bin/env npx ts-node
/**
 * review-tables — the side-by-side copy review for one scope (8.2, plan
 * Component 2) and the shared glossary page.
 *
 *   review-tables.ts --project-root <p> --scope <s> --glossary <file>
 *                    --out <dir> [--check] [--workspace-root <dir>]
 *
 * Writes `<out>/<scope>.md` (`key | English | Arabic | notes`, one row per key
 * of `en.json` or `ar.json`, sorted by key) and `<out>/glossary.md`
 * (`term | reason`, sorted by term). With `--check` it writes nothing and
 * exits 1 when either committed file differs from a fresh generation.
 *
 * Invocation for a lib batch, from the workspace root:
 *
 *   node_modules/.bin/nx run i18n-check:review-tables -- \
 *     --project-root libs/web/pricing --scope pricing \
 *     --glossary tools/i18n-check/glossary.json \
 *     --out .ptah/specs/TASK_2026_575_fee7/copy-review
 *
 * and the same command with `--check` to verify the committed tables.
 *
 * Output is byte-for-byte deterministic: no dates, workspace-relative paths,
 * keys and terms in code-unit order, notes from fixed rules. It is formatted
 * with the workspace's Prettier (markdown parser), so the pre-commit
 * `nx format:write` leaves the generated bytes unchanged.
 *
 * `--out`, `--glossary` and `--project-root` resolve against
 * `--workspace-root` (default: the current directory). Exit 0 when written or
 * up to date; 1 on drift, on any violation in the scope's `en.json` or
 * `ar.json` or the glossary (nothing is written), or when Prettier cannot
 * format the output; 2 on a usage error.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as markdownPlugin from 'prettier/plugins/markdown';
import { format } from 'prettier/standalone';
import { containsTerm, loadGlossary, type Glossary } from '../lib/glossary';
import { UsageError, resolveProjectRoot, toRel } from '../lib/cli';
import {
  compareText,
  formatViolation,
  normaliseViolations,
  type Violation,
} from '../lib/report';
import { scopeI18nDir } from '../lib/scope-map';
import {
  loadTranslationFile,
  placeholdersOf,
  type TranslationEntry,
  type TranslationFile,
} from '../lib/translation-files';

export interface ReviewOptions {
  workspaceRoot: string;
  projectRoot: string;
  scope: string;
  glossary: string;
  out: string;
  check: boolean;
}

/** One generated file, by workspace-relative path. */
export interface ReviewFile {
  path: string;
  content: string;
}

/** The legal governing-language notice (8.4, design-spec §3.8). */
export const LEGAL_NOTICE_KEY = 'legal.governingLanguageNotice';

const GENERATED_NOTICE =
  '<!-- Generated by tools/i18n-check/src/review/review-tables.ts. Do not edit by hand: regenerate with the command in that file. -->';

const USAGE =
  'usage: review-tables.ts --project-root <p> --scope <s> --glossary <file> --out <dir> [--check] [--workspace-root <dir>]';

const VALUE_FLAGS = [
  '--project-root',
  '--scope',
  '--glossary',
  '--out',
  '--workspace-root',
];

export function parseArgs(argv: readonly string[]): ReviewOptions {
  const values = new Map<string, string>();
  let check = false;
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i];
    if (flag === '--check') {
      check = true;
      continue;
    }
    if (!VALUE_FLAGS.includes(flag)) {
      throw new UsageError(`unknown argument "${flag}"`);
    }
    const value = argv[i + 1] as string | undefined;
    if (value === undefined || value.startsWith('--')) {
      throw new UsageError(`${flag} needs a value`);
    }
    values.set(flag, value);
    i += 1;
  }

  const projectRoot = values.get('--project-root');
  const scope = values.get('--scope');
  const glossary = values.get('--glossary');
  const out = values.get('--out');
  if (!projectRoot || !scope || !glossary || !out) {
    throw new UsageError(
      '--project-root, --scope, --glossary and --out are required',
    );
  }
  const normalisedRoot = resolveProjectRoot(scope, projectRoot);
  return {
    workspaceRoot: path.resolve(
      values.get('--workspace-root') ?? process.cwd(),
    ),
    projectRoot: normalisedRoot,
    scope,
    glossary,
    out,
    check,
  };
}

/**
 * The notes for one key, in a fixed order: presence, identical to English,
 * glossary terms in the English value, placeholders, and the legal notice.
 * An invalid value never reaches a table: `generate` refuses the file.
 */
export function reviewNotes(
  key: string,
  en: TranslationEntry | undefined,
  ar: TranslationEntry | undefined,
  glossary: Glossary,
): string[] {
  const notes: string[] = [];
  if (!en) notes.push('missing in English');
  if (!ar) notes.push('missing in Arabic');

  const enValue = en?.value ?? null;
  const arValue = ar?.value ?? null;
  if (enValue !== null && enValue === arValue) {
    notes.push('identical to English');
  }
  if (enValue !== null) {
    const terms = glossary.entries
      .map((entry) => entry.term)
      .filter((term) => containsTerm(enValue, term))
      .sort(compareText);
    if (terms.length > 0) notes.push(`glossary: ${terms.join(', ')}`);
  }
  const placeholderSource = enValue ?? arValue;
  if (placeholderSource !== null) {
    const names = placeholdersOf(placeholderSource);
    if (names.length > 0) notes.push(`placeholders: ${names.join(', ')}`);
  }
  if (key === LEGAL_NOTICE_KEY) {
    notes.push('legal governing-language notice (8.4)');
  }
  return notes;
}

/**
 * A value shown literally in a table cell: Markdown and HTML are escaped, so
 * `<strong>` reads as markup to review rather than rendering, and a line
 * break (LF, CRLF, U+2028, U+2029) becomes `<br>`.
 */
export function tableCell(value: string): string {
  return value
    .replace(/[\\`*_[\]~|]/g, '\\$&')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\r?\n|\u2028|\u2029/g, '<br>');
}

function valueCell(entry: TranslationEntry | undefined): string {
  return entry?.value == null ? '' : tableCell(entry.value);
}

export function renderScopeTable(
  scope: string,
  en: TranslationFile,
  ar: TranslationFile,
  glossary: Glossary,
  glossaryPath: string,
): string {
  const keys = [...new Set([...en.entries.keys(), ...ar.entries.keys()])].sort(
    compareText,
  );
  const rows = keys.map((key) => {
    const enEntry = en.entries.get(key);
    const arEntry = ar.entries.get(key);
    const notes = reviewNotes(key, enEntry, arEntry, glossary);
    return `| \`${key}\` | ${valueCell(enEntry)} | ${valueCell(arEntry)} | ${tableCell(notes.join('; '))} |`;
  });
  return [
    `# Copy review: \`${scope}\``,
    '',
    GENERATED_NOTICE,
    '',
    `- English: \`${en.file}\``,
    `- Arabic: \`${ar.file}\``,
    `- Glossary: \`${glossaryPath}\` (see \`glossary.md\`)`,
    `- Keys: ${keys.length}`,
    '',
    '| key | English | Arabic | notes |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

export function renderGlossary(
  glossary: Glossary,
  glossaryPath: string,
): string {
  const entries = [...glossary.entries].sort((a, b) =>
    compareText(a.term, b.term),
  );
  return [
    '# Glossary',
    '',
    GENERATED_NOTICE,
    '',
    `Terms copied verbatim into every Arabic value (\`${glossaryPath}\`).`,
    '',
    '| term | reason |',
    '| --- | --- |',
    ...entries.map((e) => `| ${tableCell(e.term)} | ${tableCell(e.reason)} |`),
    '',
  ].join('\n');
}

/**
 * The file's Prettier-formatted content, or a `format-error` naming the file
 * when Prettier throws: that failure is this output's, not an internal error.
 */
async function formatMarkdown(
  text: string,
  file: string,
  scope: string,
): Promise<string | Violation> {
  try {
    return await format(text, {
      parser: 'markdown',
      plugins: [markdownPlugin],
    });
  } catch (error: unknown) {
    return {
      file,
      line: 0,
      kind: 'format-error',
      key: '',
      detail: `Prettier could not format the generated markdown for scope "${scope}": ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * The two review files for a scope, or the violations that prevent
 * generating them. Any violation in the scope's `en.json` or `ar.json`
 * refuses generation, not only an unreadable file: a key the loader rejects
 * (`dotted-key`, `duplicate-key`, `invalid-value`, `sole-default-key`) would
 * otherwise be missing from, or misrepresented in, the table a reviewer signs.
 */
export async function generate(
  options: ReviewOptions,
): Promise<{ files: ReviewFile[]; violations: Violation[] }> {
  const glossaryAbs = path.resolve(options.workspaceRoot, options.glossary);
  const glossaryPath = toRel(options.workspaceRoot, glossaryAbs);
  const glossary = loadGlossary(glossaryAbs, glossaryPath);

  const load = (lang: 'en' | 'ar'): TranslationFile => {
    const rel = `${scopeI18nDir(options.scope)}/${lang}.json`;
    return loadTranslationFile(
      path.join(options.workspaceRoot, rel),
      rel,
      options.scope,
    );
  };
  const en = load('en');
  const ar = load('ar');

  const violations = [
    ...glossary.violations,
    ...en.violations,
    ...ar.violations,
  ];
  if (violations.length > 0) {
    return { files: [], violations: normaliseViolations(violations) };
  }

  const outAbs = path.resolve(options.workspaceRoot, options.out);
  const outRel = (name: string): string =>
    toRel(options.workspaceRoot, path.join(outAbs, name));
  const drafts: ReviewFile[] = [
    {
      path: outRel(`${options.scope}.md`),
      content: renderScopeTable(options.scope, en, ar, glossary, glossaryPath),
    },
    {
      path: outRel('glossary.md'),
      content: renderGlossary(glossary, glossaryPath),
    },
  ];
  const files: ReviewFile[] = [];
  for (const draft of drafts) {
    const formatted = await formatMarkdown(
      draft.content,
      draft.path,
      options.scope,
    );
    if (typeof formatted === 'string') {
      files.push({ path: draft.path, content: formatted });
    } else {
      violations.push(formatted);
    }
  }
  return violations.length > 0
    ? { files: [], violations }
    : { files, violations: [] };
}

/** Writes (or, with `check`, compares) the review files; returns the exit code and report lines. */
export async function reviewTables(
  options: ReviewOptions,
): Promise<{ code: number; lines: string[] }> {
  const label = `review-tables [${options.scope}]`;
  const { files, violations } = await generate(options);
  if (violations.length > 0) {
    return {
      code: 1,
      lines: [
        ...violations.map(formatViolation),
        `${label}: nothing generated; fix the violation(s) above first`,
      ],
    };
  }

  const absOf = (file: ReviewFile): string =>
    path.join(options.workspaceRoot, file.path);
  if (!options.check) {
    for (const file of files) {
      fs.mkdirSync(path.dirname(absOf(file)), { recursive: true });
      fs.writeFileSync(absOf(file), file.content, 'utf8');
    }
    return {
      code: 0,
      lines: files.map((file) => `${label}: wrote ${file.path}`),
    };
  }

  const drifted = files.filter((file) => {
    const abs = absOf(file);
    return !fs.existsSync(abs) || fs.readFileSync(abs, 'utf8') !== file.content;
  });
  if (drifted.length === 0) {
    return {
      code: 0,
      lines: [`${label}: OK (${files.map((f) => f.path).join(', ')})`],
    };
  }
  return {
    code: 1,
    lines: [
      ...drifted.map(
        (file) =>
          `${file.path}: out of date with a fresh generation; rerun review-tables without --check and commit the result`,
      ),
      `${label}: ${drifted.length} file(s) out of date`,
    ],
  };
}

async function main(): Promise<number> {
  let options: ReviewOptions;
  try {
    options = parseArgs(process.argv.slice(2));
  } catch (error: unknown) {
    if (error instanceof UsageError) {
      console.error(`review-tables: ${error.message}\n${USAGE}`);
      return 2;
    }
    throw error;
  }
  const { code, lines } = await reviewTables(options);
  for (const line of lines) console.log(line);
  return code;
}

// Imported by the spec; executed as the CLI entry point.
if (require.main === module) {
  main()
    .then((code) => process.exit(code))
    .catch((error: unknown) => {
      console.error('review-tables: internal error', error);
      process.exit(2);
    });
}
