import nx from '@nx/eslint-plugin';
import baseConfig from '../../../eslint.config.mjs';
import angularConfig from '../../../eslint.angular.config.mjs';

// Generated by tools/migration/extract-domain.ts.
// `angularConfig` is the same Angular rule posture apps/ptah-landing-page lints under,
// so moving a file into this lib does not change how it is linted.
export default [
  ...baseConfig,
  ...nx.configs['flat/angular'],
  ...nx.configs['flat/angular-template'],
  ...angularConfig,
  {
    files: ['**/*.ts'],
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: ['app', 'ptah'], style: 'camelCase' },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: ['app', 'ptah'], style: 'kebab-case' },
      ],
    },
  },
];
