/**
 * HarnessPromptBuilderService.
 *
 * Pure functions (wrapped in an injectable for DI symmetry + future state)
 * that build the structured system-prompt sections and the CLAUDE.md content
 * from a harness config.
 *
 * Extracted from `harness-rpc.handlers.ts` (lines 1999–2159).
 */

import { injectable } from 'tsyringe';
import type {
  HarnessConfig,
  HarnessGeneratePromptParams,
} from '@ptah-extension/shared';

@injectable()
export class HarnessPromptBuilderService {
  /**
   * Build system prompt sections from persona, agents, and skills.
   */
  buildPromptSections(
    persona: HarnessGeneratePromptParams['persona'],
    enabledAgents: string[],
    selectedSkills: string[],
  ): Record<string, string> {
    const sections: Record<string, string> = {};

    // Persona section
    sections['persona'] = [
      `# ${persona.label}`,
      '',
      persona.description,
      '',
      persona.goals.length > 0
        ? `## Goals\n${persona.goals.map((g) => `- ${g}`).join('\n')}`
        : '',
    ]
      .filter(Boolean)
      .join('\n');

    // Agents section
    if (enabledAgents.length > 0) {
      sections['agents'] = [
        '## Available Agents',
        '',
        ...enabledAgents.map((agentId) => `- **${agentId}**: Enabled`),
      ].join('\n');
    }

    // Skills section
    if (selectedSkills.length > 0) {
      sections['skills'] = [
        '## Active Skills',
        '',
        ...selectedSkills.map((skillId) => `- ${skillId}`),
      ].join('\n');
    }

    // Instructions section
    sections['instructions'] = [
      '## Instructions',
      '',
      'Follow the configured persona and goals when responding.',
      'Use available agents for specialized tasks.',
      'Apply active skills when relevant to the user request.',
    ].join('\n');

    return sections;
  }

  /**
   * Build CLAUDE.md content from harness config.
   */
  buildClaudeMdContent(
    config: Omit<HarnessConfig, 'claudeMd' | 'createdAt' | 'updatedAt'>,
  ): string {
    const lines: string[] = [];

    // Header
    lines.push(`# ${config.name}`);
    lines.push('');
    lines.push(
      `> Generated by Ptah Harness Builder on ${new Date().toISOString().split('T')[0]}`,
    );
    lines.push('');

    // Persona
    lines.push('## Persona');
    lines.push('');
    lines.push(`**${config.persona.label}**`);
    lines.push('');
    lines.push(config.persona.description);
    lines.push('');
    if (config.persona.goals.length > 0) {
      lines.push('### Goals');
      lines.push('');
      for (const goal of config.persona.goals) {
        lines.push(`- ${goal}`);
      }
      lines.push('');
    }

    // Agents
    const enabledAgentIds = Object.entries(config.agents.enabledAgents)
      .filter(([, override]) => override.enabled)
      .map(([id]) => id);

    if (enabledAgentIds.length > 0) {
      lines.push('## Agents');
      lines.push('');
      for (const agentId of enabledAgentIds) {
        const override = config.agents.enabledAgents[agentId];
        const details: string[] = [];
        if (override.modelTier) details.push(`tier: ${override.modelTier}`);
        if (override.autoApprove) details.push('auto-approve: yes');
        const suffix = details.length > 0 ? ` (${details.join(', ')})` : '';
        lines.push(`- **${agentId}**${suffix}`);
      }
      lines.push('');
    }

    // Harness Subagent Fleet
    const harnessSubagents = config.agents.harnessSubagents ?? [];
    if (harnessSubagents.length > 0) {
      lines.push('## Harness Subagent Fleet');
      lines.push('');
      for (const sub of harnessSubagents) {
        lines.push(`### ${sub.name}`);
        lines.push('');
        lines.push(sub.description);
        lines.push('');
        lines.push(`- **Role**: ${sub.role}`);
        lines.push(`- **Execution Mode**: ${sub.executionMode}`);
        lines.push(`- **Tools**: ${sub.tools.join(', ')}`);
        if (sub.triggers && sub.triggers.length > 0) {
          lines.push(`- **Triggers**: ${sub.triggers.join(', ')}`);
        }
        lines.push('');
        lines.push(`**Instructions**: ${sub.instructions}`);
        lines.push('');
      }
    }

    // Skills
    if (config.skills.selectedSkills.length > 0) {
      lines.push('## Skills');
      lines.push('');
      for (const skillId of config.skills.selectedSkills) {
        lines.push(`- ${skillId}`);
      }
      lines.push('');
    }

    // System Prompt
    if (config.prompt.systemPrompt) {
      lines.push('## System Prompt');
      lines.push('');
      lines.push(config.prompt.systemPrompt);
      lines.push('');
    }

    // MCP Servers
    const enabledServers = config.mcp.servers.filter((s) => s.enabled);
    if (enabledServers.length > 0) {
      lines.push('## MCP Servers');
      lines.push('');
      for (const server of enabledServers) {
        lines.push(`- **${server.name}**: ${server.description || server.url}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }
}
