/**
 * The two plain documents `vendor-brand-icons.mjs` writes besides the TS table:
 *
 * - the SHIPPED notices file (plain text, packaged into the VS Code VSIX and the
 *   desktop app). It carries theSVG's licence and names every vendored mark
 *   whose own licence asks for attribution or notice. Because it is not
 *   JavaScript, it must never name an AI vendor (the Marketplace scanner rule,
 *   `scanner-tokens.mjs`): an AI-vendor mark under a permissive licence is
 *   covered by the generic theSVG notice without being named, and an AI-vendor
 *   mark whose licence REQUIRES naming it is a problem that aborts the run.
 * - the NOT-shipped rejection report (Markdown under `scripts/brand-icons/`), the
 *   persisted record of every rejected variant and every monogram.
 *
 * Pure functions; the caller formats, guards and writes.
 */

import { findScannerTokens } from './scanner-tokens.mjs';

/** Licences that ask for nothing: the mark is not named. */
const PUBLIC_DOMAIN = new Set(['cc0-1.0', 'unlicense', '0bsd', 'pddl-1.0']);
/** Licences satisfied by reproducing a licence text: named unless the brand is an AI vendor. */
const PERMISSIVE = /^(mit|isc|bsd-[0-3]-clause|apache-2\.0)$/i;

/** `public-domain`, `permissive`, or `notice-required` (CC-BY, LGPL, trademark terms, undeclared, ...). */
export function licenceClass(licenceId) {
  const id = (licenceId ?? '').trim();
  if (PUBLIC_DOMAIN.has(id.toLowerCase())) return 'public-domain';
  if (PERMISSIVE.test(id)) return 'permissive';
  return 'notice-required';
}

const iconsUrl = (source) =>
  `https://github.com/${source.repository}/tree/${source.commit}/public/icons`;

/**
 * Decides which vendored marks the notices file names.
 * Returns `{ named, unnamedCount, problems }`.
 */
export function selectNamedMarks(outcomes) {
  const named = [];
  const problems = [];
  let unnamedCount = 0;
  for (const outcome of outcomes.filter((o) => o.record)) {
    const { title, url, licenceId } = outcome.plan.brand;
    const cls = licenceClass(licenceId);
    const aiVendor =
      findScannerTokens(`${outcome.slug} ${title} ${url}`).length > 0;
    if (cls === 'public-domain' || (cls === 'permissive' && aiVendor)) {
      unnamedCount++;
    } else if (cls === 'notice-required' && aiVendor) {
      problems.push(
        `"${outcome.slug}" (${licenceId}) must be named in the shipped notices, ` +
          'but its name is a Marketplace-scanner token; make it a monogram in the manifest',
      );
    } else {
      named.push({ outcome, title, url, licenceId, cls });
    }
  }
  return { named, unnamedCount, problems };
}

/** The shipped plain-text notices. Deterministic for a given input. */
export function renderNotices({ source, licenseText, selection }) {
  const underline = (text, char) => [text, char.repeat(text.length)];
  const entries = selection.named.flatMap(
    ({ outcome, title, url, licenceId }) => [
      title,
      `  Licence: ${licenceId || 'not declared by theSVG'}`,
      ...(url ? [`  Brand:   ${url}`] : []),
      `  Artwork: ${iconsUrl(source)}/${outcome.slug}`,
      '',
    ],
  );
  return [
    ...underline('BRAND ICON NOTICES', '='),
    '',
    'Generated by scripts/vendor-brand-icons.mjs. Do not edit by hand.',
    '',
    'Ptah shows brand marks only to identify the product or service a user',
    'connects to (nominative use). Every mark is a trademark of its respective',
    'owner. Showing a mark implies no endorsement by, or affiliation with, its',
    'owner.',
    '',
    `The marks were vendored from theSVG (https://github.com/${source.repository})`,
    `at commit ${source.commit}, pinned ${source.pinnedOn}:`,
    iconsUrl(source),
    '',
    ...underline('1. theSVG licence', '-'),
    '',
    'The SVG code of every vendored mark is provided by theSVG under the',
    'following licence:',
    '',
    ...licenseText
      .trim()
      .split(/\r?\n/)
      .map((line) => line.trimEnd()),
    '',
    ...underline('2. Marks with their own licence terms', '-'),
    '',
    "The marks below carry licence terms of their own, as declared by theSVG's",
    'index (src/data/icons.json) at the commit above.',
    '',
    ...(entries.length ? entries : ['None.', '']),
    ...underline('3. All other marks', '-'),
    '',
    `The other ${selection.unnamedCount} vendored marks are published by theSVG under a`,
    'public-domain dedication (CC0-1.0) or a permissive licence satisfied by the',
    'theSVG licence text in section 1.',
    '',
  ].join('\n');
}

/** The run summary printed to stdout (the persisted form is the rejection report). */
export function formatConsoleReport({
  source,
  outcomes,
  a4,
  output,
  bytes,
  budget,
}) {
  const vendored = outcomes.filter((o) => o.record);
  const list = (items) => (items.length ? items.join(', ') : 'none');
  const slugsWhere = (predicate) =>
    list(vendored.filter(predicate).map((o) => o.slug));
  const rejections = outcomes.flatMap((o) =>
    o.rejections.map(
      (r) => `  ${o.slug}/${r.variant}: ${r.reason} -> ${r.fallback}`,
    ),
  );
  const monograms = outcomes
    .filter((o) => !o.record)
    .map((o) => `${o.slug} (${o.notes[0] ?? 'every variant rejected'})`);
  const providers = vendored
    .filter((o) => o.plan.icon.groups.includes('provider'))
    .map((o) => `${o.slug} (${o.record.mono ? 'mono' : 'art'})`);
  return [
    `theSVG ${source.repository}@${source.commit}: ${outcomes.length} slugs, ` +
      `${vendored.length} vendored, ${outcomes.length - vendored.length} monogram`,
    a4,
    `Rejections:\n${rejections.length ? rejections.join('\n') : '  none'}`,
    `Monograms: ${list(monograms)}`,
    `surface light: ${slugsWhere((o) => o.record.surface === 'light')}`,
    `onDark: ${slugsWhere((o) => o.record.onDark)}`,
    `mono: ${slugsWhere((o) => o.record.mono)}`,
    `PROVIDER_BRAND_ART: ${list(providers)}`,
    `Output: ${output} (${bytes} bytes, budget ${budget})`,
  ].join('\n');
}

const cell = (text) => String(text).replace(/\|/g, '\\|');

/** The persisted rejection report (Markdown; prettier formats it). Not shipped. */
export function renderRejectionReport({ source, outcomes, a4 }) {
  const vendored = outcomes.filter((o) => o.record);
  const monograms = outcomes.filter((o) => !o.record);
  const rejections = outcomes.flatMap((o) =>
    o.rejections.map(
      (r) =>
        `| ${o.slug} | ${r.variant} | ${cell(r.reason)} | ${cell(r.fallback)} |`,
    ),
  );
  const list = (items) => (items.length ? items.join(', ') : 'none');
  const slugsWhere = (predicate) =>
    list(vendored.filter(predicate).map((o) => `\`${o.slug}\``));
  return [
    '<!-- GENERATED by scripts/vendor-brand-icons.mjs from scripts/brand-icons.manifest.json. Do not edit by hand. Not shipped. -->',
    '',
    '# Brand icon rejection report',
    '',
    `theSVG \`${source.repository}\` at commit \`${source.commit}\` (pinned ${source.pinnedOn}): ` +
      `${outcomes.length} slugs, ${vendored.length} vendored, ${monograms.length} monogram.`,
    '',
    a4,
    '',
    '## Rejected variants',
    '',
    '| Slug | Variant | Reason | Fallback |',
    '| --- | --- | --- | --- |',
    ...(rejections.length ? rejections : ['| none | | | |']),
    '',
    '## Monograms',
    '',
    '| Slug | Why |',
    '| --- | --- |',
    ...monograms.map(
      (o) =>
        `| ${o.slug} | ${cell(o.plan.icon.monogram ?? 'every usable variant was rejected (see above)')} |`,
    ),
    '',
    '## Tile data',
    '',
    `- surface \`light\` (white tile): ${slugsWhere((o) => o.record.surface === 'light')}`,
    `- \`onDark\` artwork: ${slugsWhere((o) => o.record.onDark)}`,
    `- \`mono\` artwork: ${slugsWhere((o) => o.record.mono)}`,
    '',
  ].join('\n');
}
