/**
 * Runtime projections of the account response schemas generated by
 * packaged `codex-cli 0.147.0 app-server generate-json-schema`.
 * Only fields Ptah consumes are retained; Zod strips unknown future fields.
 */
import { z } from 'zod';

export const CODEX_ACCOUNT_PROTOCOL_VERSION = '0.147.0';

export const CODEX_ACCOUNT_USAGE_SUMMARY_INT64_FIELDS = [
  'lifetimeTokens', 'currentStreakDays', 'longestStreakDays',
  'peakDailyTokens', 'longestRunningTurnSec',
] as const;
export const CODEX_ACCOUNT_USAGE_DAILY_INT64_FIELDS = ['tokens'] as const;
export const CODEX_ACCOUNT_USAGE_INT64_FIELDS = [
  ...CODEX_ACCOUNT_USAGE_SUMMARY_INT64_FIELDS,
  ...CODEX_ACCOUNT_USAGE_DAILY_INT64_FIELDS,
] as const;

// The generated JSON schema declares these as int64 JSON integers. Preserve
// their raw decimal spelling before JSON.parse can round values above 2^53.
const int64Decimal = z.union([
  z.string().regex(/^\d+$/),
  z.number().int().nonnegative().safe(),
]).transform(String);

const planType = z.enum([
  'free', 'go', 'plus', 'pro', 'prolite', 'team',
  'self_serve_business_prolite', 'self_serve_business_usage_based',
  'business', 'ent26', 'enterprise_cbp_automation',
  'enterprise_cbp_usage_based', 'enterprise', 'edu', 'unknown',
]);

export const codexAccountResponseSchema = z.object({
  account: z.discriminatedUnion('type', [
    z.object({ type: z.literal('apiKey') }),
    z.object({ type: z.literal('chatgpt'), email: z.string().nullable(), planType }),
    z.object({ type: z.literal('amazonBedrock'), usesCodexManagedCredentials: z.boolean().default(false) }),
  ]).nullable().optional(),
  requiresOpenaiAuth: z.boolean(),
});

const rateLimitWindow = z.object({
  usedPercent: z.number().int(),
  windowDurationMins: z.number().int().nullable().optional(),
  resetsAt: z.number().int().nullable().optional(),
});

const rateLimitSnapshot = z.object({
  limitId: z.string().nullable().optional(),
  limitName: z.string().nullable().optional(),
  planType: planType.nullable().optional(),
  primary: rateLimitWindow.nullable().optional(),
  secondary: rateLimitWindow.nullable().optional(),
  credits: z.object({
    hasCredits: z.boolean(), unlimited: z.boolean(), balance: z.string().nullable().optional(),
  }).nullable().optional(),
  spendControlReached: z.boolean().nullable().optional(),
});

export const codexRateLimitsResponseSchema = z.object({
  rateLimits: rateLimitSnapshot,
  rateLimitsByLimitId: z.record(z.string(), rateLimitSnapshot).nullable().optional(),
});

const summaryInt64Shape = {
  lifetimeTokens: int64Decimal.nullable().optional(),
  currentStreakDays: int64Decimal.nullable().optional(),
  longestStreakDays: int64Decimal.nullable().optional(),
  peakDailyTokens: int64Decimal.nullable().optional(),
  longestRunningTurnSec: int64Decimal.nullable().optional(),
} satisfies Record<(typeof CODEX_ACCOUNT_USAGE_SUMMARY_INT64_FIELDS)[number], z.ZodType>;
const dailyInt64Shape = {
  tokens: int64Decimal,
} satisfies Record<(typeof CODEX_ACCOUNT_USAGE_DAILY_INT64_FIELDS)[number], z.ZodType>;

export const codexTokenUsageResponseSchema = z.object({
  summary: z.object(summaryInt64Shape),
  dailyUsageBuckets: z.array(z.object({
    startDate: z.string(), ...dailyInt64Shape,
  })).nullable().optional(),
});

export const codexInitializeResponseSchema = z.object({
  userAgent: z.string(), codexHome: z.string(), platformFamily: z.string(), platformOs: z.string(),
});

export type CodexAccountResponse = z.infer<typeof codexAccountResponseSchema>;
export type CodexRateLimitsResponse = z.infer<typeof codexRateLimitsResponseSchema>;
export type CodexTokenUsageResponse = z.infer<typeof codexTokenUsageResponseSchema>;
