// Attribute generated bytes in a bundle chunk to its original sources via the source map.
// Decodes VLQ mappings, assigns each generated segment's byte span to the source it maps to.
const fs = require('fs');
const path = require('path');

const B64 = {};
'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
  .split('')
  .forEach((c, i) => (B64[c] = i));

function decodeVLQ(str) {
  const out = [];
  let shift = 0,
    value = 0;
  for (const c of str) {
    const d = B64[c];
    if (d === undefined) continue;
    const cont = d & 32;
    value += (d & 31) << shift;
    if (cont) {
      shift += 5;
    } else {
      const neg = value & 1;
      value >>= 1;
      out.push(neg ? (value === 0 ? -0x80000000 : -value) : value);
      value = 0;
      shift = 0;
    }
  }
  return out;
}

function bucket(src) {
  if (!src) return '<unmapped>';
  const s = src.replace(/\\/g, '/');
  let m = s.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
  if (m) return 'npm:' + m[1];
  m = s.match(/libs\/frontend\/([^/]+)/);
  if (m) return 'lib:frontend/' + m[1];
  m = s.match(/libs\/shared\/?([^/]*)/);
  if (m) return 'lib:shared';
  m = s.match(/apps\/([^/]+)/);
  if (m) return 'app:' + m[1];
  if (s.startsWith('angular:')) return 'angular:generated';
  return 'other:' + s.split('/').slice(0, 3).join('/');
}

function attribute(mapFile) {
  const map = JSON.parse(fs.readFileSync(mapFile, 'utf8'));
  const jsFile = mapFile.replace(/\.map$/, '');
  const code = fs.readFileSync(jsFile, 'utf8');
  const totalBytes = Buffer.byteLength(code);
  const lines = code.split('\n');
  const lineLens = lines.map((l) => Buffer.byteLength(l) + 1);

  const sources = map.sources || [];
  const totals = new Map();
  let srcIdx = 0;

  const groups = map.mappings.split(';');
  // Collect segments as (genLine, genCol, sourceIndex)
  const segs = [];
  for (let gl = 0; gl < groups.length; gl++) {
    let genCol = 0;
    if (!groups[gl]) continue;
    for (const segStr of groups[gl].split(',')) {
      if (!segStr) continue;
      const f = decodeVLQ(segStr);
      genCol += f[0];
      if (f.length >= 4) srcIdx += f[1];
      segs.push([gl, genCol, f.length >= 4 ? srcIdx : -1]);
    }
  }

  // Each segment owns bytes until the next segment on the same line, or end of line.
  for (let i = 0; i < segs.length; i++) {
    const [gl, gc, si] = segs[i];
    const next = segs[i + 1];
    let end;
    if (next && next[0] === gl) end = next[1];
    else end = Math.max(gc, lineLens[gl] ? lineLens[gl] - 1 : gc);
    const size = Math.max(0, end - gc);
    const key = si >= 0 ? bucket(sources[si]) : '<unmapped>';
    totals.set(key, (totals.get(key) || 0) + size);
  }

  const mapped = [...totals.values()].reduce((a, b) => a + b, 0);
  totals.set('<unaccounted>', Math.max(0, totalBytes - mapped));

  return { jsFile: path.basename(jsFile), totalBytes, totals };
}

const files = process.argv.slice(2);
const grand = new Map();
for (const f of files) {
  const r = attribute(f);
  console.log(
    `\n=== ${r.jsFile}  (${(r.totalBytes / 1024).toFixed(1)} kB) ===`,
  );
  const rows = [...r.totals.entries()].sort((a, b) => b[1] - a[1]);
  for (const [k, v] of rows.slice(0, 22)) {
    if (v < 2048) continue;
    console.log(`  ${(v / 1024).toFixed(1).padStart(9)} kB  ${k}`);
  }
  for (const [k, v] of r.totals) grand.set(k, (grand.get(k) || 0) + v);
}

console.log('\n\n======== GRAND TOTAL ACROSS ALL LISTED CHUNKS ========');
for (const [k, v] of [...grand.entries()].sort((a, b) => b[1] - a[1])) {
  if (v < 4096) continue;
  console.log(`  ${(v / 1024).toFixed(1).padStart(9)} kB  ${k}`);
}
