/**
 * gen-qr.mjs — generate the end-card waitlist QR as a static SVG module.
 *
 * Runs ONCE at build time (npm run gen:qr). Encodes the waitlist URL (WITH the
 * youtube utm param, so scans are attributed) into a QR via the vendored
 * dependency-free encoder in lib/qrcode.mjs, and writes it as a tiny TS module
 * (`src/selfshot/waitlist-qr.ts`) that <EndCard> imports directly — no runtime
 * QR dep, no staticFile/staging, deterministic bundle.
 *
 * The DISPLAY url on the card is the clean `ptah.live/#waitlist` (no query
 * params); only the encoded target carries the utm tag.
 *
 * ESM, Node >=22.9.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { qrSvg, QrCode, Ecc } from './lib/qrcode.mjs';

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE = path.resolve(scriptsDir, '..', 'src', 'selfshot', 'waitlist-qr.ts');

/** Encoded target (attributed). */
const QR_URL = 'https://ptah.live/?utm_source=youtube#waitlist';
/** Clean display string on the card. */
const DISPLAY_URL = 'ptah.live/#waitlist';

function asciiPreview(qr) {
  // Two rows per line via half-block chars, for a quick eyeball sanity check.
  const lines = [];
  for (let y = 0; y < qr.size; y += 2) {
    let line = '';
    for (let x = 0; x < qr.size; x++) {
      const top = qr.getModule(x, y);
      const bot = y + 1 < qr.size ? qr.getModule(x, y + 1) : false;
      line += top && bot ? '█' : top ? '▀' : bot ? '▄' : ' ';
    }
    lines.push(line);
  }
  return lines.join('\n');
}

function main() {
  // High ECC + amber-on-ink to match the brand; still scans (dark/light contrast).
  const svg = qrSvg(QR_URL, {
    ecc: Ecc.HIGH,
    border: 2,
    dark: '#0b0d12',
    light: '#ffffff',
  });
  const qr = QrCode.encodeText(QR_URL, Ecc.HIGH);

  const banner =
    '/**\n' +
    ' * AUTO-GENERATED by scripts/gen-qr.mjs — do NOT edit by hand.\n' +
    ' * Regenerate with: npm run gen:qr (from apps/ptah-video-studio).\n' +
    ' *\n' +
    ` * Encoded target: ${QR_URL}\n` +
    ` * Displayed on card: ${DISPLAY_URL}\n` +
    ' */\n';
  const body =
    banner +
    `export const WAITLIST_QR_URL = ${JSON.stringify(QR_URL)};\n` +
    `export const WAITLIST_DISPLAY_URL = ${JSON.stringify(DISPLAY_URL)};\n` +
    `export const WAITLIST_QR_SVG = ${JSON.stringify(svg)};\n`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, body);

  console.log(`[gen-qr] wrote ${OUT_FILE}`);
  console.log(`[gen-qr] QR version ${qr.version} (${qr.size}x${qr.size} modules), mask ${qr.mask}.`);
  console.log(`[gen-qr] encoded: ${QR_URL}`);
  console.log('[gen-qr] preview (eyeball the 3 finder squares):\n');
  console.log(asciiPreview(qr));
}

try {
  main();
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`[gen-qr] FAILED: ${message}`);
  process.exitCode = 1;
}
