import { inject, injectable } from 'tsyringe';
import * as path from 'path';
import {
  PLATFORM_TOKENS,
  type IFileSystemProvider,
} from '@ptah-extension/platform-core';
import { TOKENS, type Logger } from '@ptah-extension/vscode-core';
import type { TaskSpecSummary } from '@ptah-extension/shared';
import { normalizeWorkspaceRoot } from './normalize-workspace-root';
import { TaskScannerService } from './task-scanner.service';

export interface GenerateRegistryResult {
  /** workspace-relative path (no absolute-path leakage, R4.4). */
  registryPath: string;
  includedCount: number;
  excludedCount: number;
  /** true when the file was (re)written; false when unchanged (write-if-changed). */
  changed: boolean;
}

/** Workspace-relative registry location (posix form for stable results). */
const REGISTRY_REL_PATH = '.ptah/specs/registry.md';

/**
 * Generates the derived `registry.md` table from `task.md` frontmatter
 * (R2.1–R2.5). Deterministic: two runs over unchanged files produce
 * byte-identical output (the header "last content change" is `max(updated)` of
 * included tasks — a pure function of inputs, NOT wall-clock now). Ordering is
 * newest-first by `created`, with null-created tasks last alphabetically by
 * folder. Writes only when content changed to avoid watcher self-trigger.
 */
@injectable()
export class RegistryGeneratorService {
  constructor(
    @inject(PLATFORM_TOKENS.FILE_SYSTEM_PROVIDER)
    private readonly fs: IFileSystemProvider,
    @inject(TOKENS.LOGGER)
    private readonly logger: Logger,
    private readonly scanner: TaskScannerService,
  ) {}

  async generate(workspaceRoot: string): Promise<GenerateRegistryResult> {
    const root = normalizeWorkspaceRoot(workspaceRoot);
    const { tasks, excluded } = await this.scanner.scan(root);

    const ordered = this.orderTasks(tasks);
    const content = this.render(ordered, excluded.length);

    const absPath = path.join(root, '.ptah', 'specs', 'registry.md');
    let changed = true;
    try {
      if (await this.fs.exists(absPath)) {
        const current = await this.fs.readFile(absPath);
        if (current === content) changed = false;
      }
      if (changed) {
        await this.fs.writeFile(absPath, content);
      }
    } catch (error: unknown) {
      this.logger.error(
        '[task-specs] registry write failed',
        error instanceof Error ? error : new Error(String(error)),
      );
    }

    return {
      registryPath: REGISTRY_REL_PATH,
      includedCount: tasks.length,
      excludedCount: excluded.length,
      changed,
    };
  }

  /** Newest-first by `created`; null-created last, alphabetical by folder. */
  private orderTasks(tasks: TaskSpecSummary[]): TaskSpecSummary[] {
    return [...tasks].sort((a, b) => {
      if (a.created && b.created) {
        if (a.created === b.created)
          return a.folderName.localeCompare(b.folderName);
        return a.created < b.created ? 1 : -1;
      }
      if (a.created && !b.created) return -1;
      if (!a.created && b.created) return 1;
      return a.folderName.localeCompare(b.folderName);
    });
  }

  private render(tasks: TaskSpecSummary[], excludedCount: number): string {
    const lastChange = this.maxUpdated(tasks) ?? '-';
    const lines: string[] = [];
    lines.push(
      '<!-- GENERATED by Ptah tasks:generateRegistry — DO NOT HAND-EDIT. Derived from TASK_*/task.md frontmatter. -->',
    );
    lines.push(`<!-- Last content change: ${lastChange} -->`);
    lines.push('');
    lines.push('# Task Registry');
    lines.push('');
    lines.push('| Task ID | Status | Type | Title | Created | Updated |');
    lines.push('|---|---|---|---|---|---|');
    for (const task of tasks) {
      lines.push(
        `| ${task.id} | ${task.status} | ${task.type ?? '-'} | ${this.escape(
          task.title,
        )} | ${task.created ?? '-'} | ${task.updated ?? '-'} |`,
      );
    }
    lines.push('');
    lines.push(
      `_Excluded (no valid frontmatter): ${excludedCount} folder(s)._`,
    );
    lines.push('');
    return lines.join('\n');
  }

  private maxUpdated(tasks: TaskSpecSummary[]): string | null {
    let max: string | null = null;
    for (const task of tasks) {
      if (task.updated && (max === null || task.updated > max)) {
        max = task.updated;
      }
    }
    return max;
  }

  /** Escape markdown table-breaking pipe characters in free text. */
  private escape(text: string): string {
    return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
  }
}
