import * as path from 'path';
import { createMockFileSystemProvider } from '@ptah-extension/platform-core/testing';
import type { Logger } from '@ptah-extension/vscode-core';
import { normalizeWorkspaceRoot } from './normalize-workspace-root';
import { TaskScannerService } from './task-scanner.service';
import { RegistryGeneratorService } from './registry-generator.service';

function makeLogger(): Logger {
  return {
    debug: jest.fn(),
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  } as unknown as Logger;
}

const ROOT = 'd:/tmp/ws-registry';

function specsDir(): string {
  return path.join(normalizeWorkspaceRoot(ROOT), '.ptah', 'specs');
}

function carrier(folder: string): string {
  return path.join(specsDir(), folder, 'task.md');
}

function task(id: string, created: string, updated: string): string {
  return [
    '---',
    'status: in_progress',
    'type: FEATURE',
    `title: ${id} title`,
    `created: '${created}'`,
    `updated: '${updated}'`,
    '---',
    'body',
  ].join('\n');
}

async function seed(fs: ReturnType<typeof createMockFileSystemProvider>) {
  await fs.writeFile(
    carrier('TASK_2026_001'),
    task(
      'TASK_2026_001',
      '2026-01-01T00:00:00.000Z',
      '2026-03-01T00:00:00.000Z',
    ),
  );
  await fs.writeFile(
    carrier('TASK_2026_002'),
    task(
      'TASK_2026_002',
      '2026-02-01T00:00:00.000Z',
      '2026-02-15T00:00:00.000Z',
    ),
  );
  // Excluded folder (no carrier).
  await fs.createDirectory(path.join(specsDir(), 'TASK_LEGACY'));
}

function makeGenerator(fs: ReturnType<typeof createMockFileSystemProvider>) {
  const logger = makeLogger();
  const scanner = new TaskScannerService(fs, logger);
  return new RegistryGeneratorService(fs, logger, scanner);
}

describe('RegistryGeneratorService', () => {
  it('emits a GENERATED header, ordered rows, and an excluded summary', async () => {
    const fs = createMockFileSystemProvider();
    await seed(fs);
    const generator = makeGenerator(fs);

    const result = await generator.generate(ROOT);
    expect(result.includedCount).toBe(2);
    expect(result.excludedCount).toBe(1);
    expect(result.registryPath).toBe('.ptah/specs/registry.md');

    const content = await fs.readFile(path.join(specsDir(), 'registry.md'));
    expect(content).toContain('<!-- GENERATED by Ptah tasks:generateRegistry');
    // max(updated) header freshness = the newer 'updated' of the two.
    expect(content).toContain('Last content change: 2026-03-01T00:00:00.000Z');
    // Newest-first by created → TASK_2026_002 (Feb) before TASK_2026_001 (Jan).
    expect(content.indexOf('TASK_2026_002')).toBeLessThan(
      content.indexOf('TASK_2026_001'),
    );
    expect(content).toContain(
      '_Excluded (no valid frontmatter): 1 folder(s)._',
    );
  });

  it('is deterministic and write-if-changed (two runs byte-identical)', async () => {
    const fs = createMockFileSystemProvider();
    await seed(fs);
    const generator = makeGenerator(fs);

    const first = await generator.generate(ROOT);
    const content1 = await fs.readFile(path.join(specsDir(), 'registry.md'));

    const second = await generator.generate(ROOT);
    const content2 = await fs.readFile(path.join(specsDir(), 'registry.md'));

    expect(first.changed).toBe(true);
    expect(second.changed).toBe(false);
    expect(content2).toBe(content1);
  });

  it('renders a dash header and zero excluded when the tree is empty', async () => {
    const fs = createMockFileSystemProvider();
    await fs.createDirectory(specsDir());
    const generator = makeGenerator(fs);

    await generator.generate(ROOT);
    const content = await fs.readFile(path.join(specsDir(), 'registry.md'));

    expect(content).toContain('Last content change: -');
    expect(content).toContain(
      '_Excluded (no valid frontmatter): 0 folder(s)._',
    );
  });
});
