/**
 * Saved board views (TASK_2026_181, FR-C2).
 *
 * ## A view is a LENS, not a cache
 *
 * A saved view stores `{ id, name, filter, sort, order }` and nothing else —
 * no task data, no task ids, no snapshot of what it matched last time
 * (FR-C2.1). Applying a view re-runs the SAME `filterTasks` predicate over
 * today's tasks, so a view can never show a task that no longer matches it, and
 * a view naming a label nobody uses any more simply matches nothing. Storing
 * results would make a view a second, staler index of the board.
 *
 * ## Why this is its own module rather than part of `task-view.types.ts`
 *
 * `batches.md` Task 8.5 names `task-view.types.ts` as the home for these three
 * exports. Putting them there creates an IMPORT CYCLE that breaks at module
 * evaluation time, not at typecheck: `task-filter.ts` already imports
 * `TaskIdRefSchema` from `task-view.types.ts` and uses it while building
 * `TaskFilterSpecSchema` at the top level, so `task-view.types.ts` importing
 * `TaskFilterSpecSchema` back would leave whichever module loaded second
 * reading an uninitialized binding — `z.array(undefined)` rather than a schema.
 * A sibling module has no such problem: it depends on both, and neither depends
 * on it, so the graph stays a DAG.
 */
import { z } from 'zod';
import { TaskFilterSpecSchema, TaskSortSpecSchema } from './task-filter';
import type { TaskFilterSpec, TaskSortSpec } from './task-filter';

/**
 * The most views one user may store (FR-C2).
 *
 * Enforced at the RPC boundary as a NAMED failure rather than as a Zod
 * `.max()`, so the user is told the list is full and what the limit is instead
 * of receiving a generic "invalid parameters" — see `TasksSaveViewsParamsSchema`.
 */
export const MAX_SAVED_TASK_VIEWS = 50;

/**
 * The longest a view id may be.
 *
 * The id is OPAQUE to this module: it is generated by the client, and it is
 * only ever compared for equality against `activeViewId`. It is never rendered,
 * never joined onto a path and never interpolated into a glob, a `RegExp` or an
 * RPC method name (BR-10), so the only property that matters here is that it is
 * bounded — an id is stored in a settings file that is read synchronously at
 * startup.
 */
export const MAX_SAVED_VIEW_ID_LENGTH = 64;

/**
 * The longest a view name may be.
 *
 * A bound on stored size and on what a menu row has to render, not a feature.
 * The name is untrusted free text and reaches the UI as `{{ interpolation }}`
 * only (BR-10).
 */
export const MAX_SAVED_VIEW_NAME_LENGTH = 60;

/**
 * One saved view.
 *
 * `order` is the field the list is presented by; it is deliberately NOT the
 * array index, because the transport for every mutation is a whole-list
 * replace and an index would then be two facts about the same thing that can
 * disagree. `tasks:getViews` returns the list sorted by it.
 */
export interface SavedTaskView {
  /** Client-generated, opaque, unique within the stored list. */
  readonly id: string;
  readonly name: string;
  readonly filter: TaskFilterSpec;
  readonly sort: TaskSortSpec;
  /** Ascending presentation order. */
  readonly order: number;
}

/**
 * The per-item validation schema (FR-C2.3, gate 3).
 *
 * This is applied ONE ENTRY AT A TIME at the RPC boundary, never to the stored
 * array as a whole. The settings layer stores `z.array(z.unknown())` on purpose
 * — see the comment on `TASKS_SAVED_VIEWS_DEF` in
 * `libs/backend/settings-core/src/schema/tasks-schema.ts` for why a strict
 * schema down there would turn one malformed view into zero surviving views.
 *
 * `filter` and `sort` are the IMPORTED shared schemas rather than restated
 * shapes, so a facet added to the board is a facet a saved view can store
 * without a second edit here. Both carry per-key defaults, which is what lets a
 * view stored before a facet existed still parse after it is added instead of
 * being counted as malformed and dropped.
 */
export const SavedTaskViewSchema = z.object({
  id: z.string().min(1).max(MAX_SAVED_VIEW_ID_LENGTH),
  name: z.string().min(1).max(MAX_SAVED_VIEW_NAME_LENGTH),
  filter: TaskFilterSpecSchema,
  sort: TaskSortSpecSchema,
  order: z.number().int().min(0),
});

/**
 * Compile-time proof that the parsed shape still satisfies the declared wire
 * type. A field added to one and not the other fails typecheck here.
 */
const _savedViewSchemaMatchesType: SavedTaskView = {} as z.infer<
  typeof SavedTaskViewSchema
>;
void _savedViewSchemaMatchesType;
