#!/usr/bin/env node
/**
 * analyze_library.mjs — objective inventory of a library / package / module folder.
 *
 * Usage:
 *   node analyze_library.mjs <path> [--max <loc>] [--top <n>] [--json]
 *
 * Reports per source file: code lines, export count, max nesting depth, longest function,
 * whether an adjacent test exists, and a SHAPE classification:
 *
 *   generated  codegen output — excluded from findings entirely
 *   types      declarations only — size is not a defect
 *   registry   flat table/dispatch — navigable at any length; down-weight
 *   logic      branching + state — this is where "god file" means something
 *
 * Line counts locate files worth reading. SHAPE decides how much a large file actually matters.
 * Strings, comments and regex literals are masked before brace counting, so depth and function
 * lengths are far more reliable than a naive scan — but this is still a heuristic, not a parser.
 * Verify anything you plan to act on by reading the file.
 *
 * Zero dependencies. Language-neutral for brace-family languages; Python uses indentation.
 */
import { readdirSync, readFileSync, statSync, existsSync } from 'node:fs';
import { join, relative, extname, basename, dirname } from 'node:path';

const args = process.argv.slice(2);
const root = args.find((a) => !a.startsWith('--') && !isValueOfFlag(a));
const asJson = args.includes('--json');
const maxLoc = num('--max', 650);
const topN = num('--top', 30);
const LONG_FN = 60;

function num(flag, fallback) {
  const i = args.indexOf(flag);
  return i === -1 ? fallback : Number(args[i + 1]) || fallback;
}
function isValueOfFlag(a) {
  const i = args.indexOf(a);
  return i > 0 && (args[i - 1] === '--max' || args[i - 1] === '--top');
}

if (!root) {
  console.error('Usage: node analyze_library.mjs <path> [--max <loc>] [--top <n>] [--json]');
  process.exit(1);
}

const BRACE_EXT = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.mts', '.cts',
  '.java', '.kt', '.kts', '.cs', '.go', '.rs', '.swift', '.scala',
  '.c', '.h', '.cpp', '.hpp', '.cc', '.m', '.php', '.dart', '.groovy',
]);
const INDENT_EXT = new Set(['.py', '.pyi']);
const OTHER_EXT = new Set(['.rb', '.vue', '.svelte', '.html', '.scss', '.css', '.sql']);
const SRC_EXT = new Set([...BRACE_EXT, ...INDENT_EXT, ...OTHER_EXT]);

const SKIP_DIR = new Set([
  'node_modules', 'dist', 'build', 'out', 'target', 'vendor', 'coverage',
  '.git', '.angular', '.next', '.nuxt', '.venv', 'venv', '__pycache__',
]);
const GENERATED_DIR = /(^|[\\/])(generated|__generated__|gen|\.gen|migrations|proto|codegen)([\\/]|$)/i;
const GENERATED_HEADER = /@generated|auto-?generated|code generated by|do not edit/i;
const TEST_FILE = /(\.|_)(spec|test|stories|e2e)\.[a-z]+$|(^|[\\/])(test_|tests?[\\/])/i;

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') && entry.name !== '.') continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIR.has(entry.name)) walk(full, out);
    } else if (SRC_EXT.has(extname(entry.name))) {
      out.push(full);
    }
  }
  return out;
}

/**
 * Replace the contents of comments, strings and regex literals with spaces, keeping line
 * structure intact. Everything downstream counts braces on the masked text, so `"}"` inside a
 * string or `/\{2,3}/` inside a regex can no longer corrupt depth and function-length counts.
 */
function maskCode(text) {
  const out = [];
  let i = 0;
  let prevMeaningful = '';
  const n = text.length;
  const space = (ch) => (ch === '\n' ? '\n' : ' ');

  while (i < n) {
    const ch = text[i];
    const next = text[i + 1];

    if (ch === '/' && next === '/') {
      while (i < n && text[i] !== '\n') out.push(space(text[i++]));
      continue;
    }
    if (ch === '/' && next === '*') {
      out.push('  ');
      i += 2;
      while (i < n && !(text[i] === '*' && text[i + 1] === '/')) out.push(space(text[i++]));
      if (i < n) {
        out.push('  ');
        i += 2;
      }
      continue;
    }
    if (ch === '#' && prevMeaningful !== '' && /[\n]/.test(text[i - 1] ?? '\n')) {
      // Python/Ruby/shell line comment (only when it opens the line's code region).
      while (i < n && text[i] !== '\n') out.push(space(text[i++]));
      continue;
    }
    if (ch === '"' || ch === "'" || ch === '`') {
      const quote = ch;
      out.push(' ');
      i++;
      while (i < n) {
        if (text[i] === '\\') {
          out.push('  ');
          i += 2;
          continue;
        }
        if (text[i] === quote) break;
        out.push(space(text[i++]));
      }
      if (i < n) {
        out.push(' ');
        i++;
      }
      continue;
    }
    if (ch === '/' && isRegexStart(prevMeaningful)) {
      out.push(' ');
      i++;
      let inClass = false;
      while (i < n && text[i] !== '\n') {
        if (text[i] === '\\') {
          out.push('  ');
          i += 2;
          continue;
        }
        if (text[i] === '[') inClass = true;
        else if (text[i] === ']') inClass = false;
        else if (text[i] === '/' && !inClass) break;
        out.push(' ');
        i++;
      }
      if (i < n && text[i] === '/') {
        out.push(' ');
        i++;
      }
      continue;
    }
    out.push(ch);
    if (!/\s/.test(ch)) prevMeaningful = ch;
    i++;
  }
  return out.join('');
}

/** A `/` opens a regex when the previous meaningful character cannot end an expression. */
function isRegexStart(prev) {
  return prev === '' || '(,=:[!&|?{};+-*%~^<>'.includes(prev);
}

function codeLines(rawLines, maskedLines) {
  let loc = 0;
  for (let i = 0; i < rawLines.length; i++) {
    const masked = (maskedLines[i] ?? '').trim();
    const raw = rawLines[i].trim();
    if (masked === '') continue;
    if (raw.startsWith('*') || raw.startsWith('#')) continue;
    loc++;
  }
  return loc;
}

function maxBraceDepth(maskedLines) {
  let depth = 0;
  let max = 0;
  for (const line of maskedLines) {
    for (const ch of line) {
      if (ch === '{') max = Math.max(max, ++depth);
      else if (ch === '}') depth = Math.max(0, depth - 1);
    }
  }
  return max;
}

function maxIndentDepth(rawLines) {
  let max = 0;
  for (const line of rawLines) {
    if (line.trim() === '' || line.trim().startsWith('#')) continue;
    const indent = line.match(/^[ \t]*/)[0].replace(/\t/g, '    ').length;
    max = Math.max(max, Math.floor(indent / 4));
  }
  return max;
}

const FN_START =
  /\b(function\b|=>\s*\{|\)\s*\{|\)\s*:\s*[\w<>,[\]\s|&.]+\{|\bfn\s+\w+|\bfunc\s+\w+|\bdef\s+\w+)/;
/** `for (...) {` also matches FN_START — a control block is not a function. */
const CONTROL_BLOCK = /\b(if|else|for|while|switch|catch|try|do|finally|with)\s*[({]/;

function longestBraceFunction(maskedLines) {
  let best = { name: '', lines: 0, at: 0 };
  for (let i = 0; i < maskedLines.length; i++) {
    const line = maskedLines[i];
    if (!FN_START.test(line) || !line.includes('{')) continue;
    if (CONTROL_BLOCK.test(line) && !/\b(function|=>)/.test(line)) continue;
    let depth = 0;
    let started = false;
    let j = i;
    for (; j < maskedLines.length; j++) {
      for (const ch of maskedLines[j]) {
        if (ch === '{') {
          depth++;
          started = true;
        } else if (ch === '}') depth--;
      }
      if (started && depth <= 0) break;
    }
    const len = j - i + 1;
    if (len > best.lines) {
      const m = line.match(/(\w+)\s*\(/);
      best = { name: m ? m[1] : '(anon)', lines: len, at: i + 1 };
    }
  }
  return best;
}

function longestIndentFunction(rawLines) {
  let best = { name: '', lines: 0, at: 0 };
  for (let i = 0; i < rawLines.length; i++) {
    const m = rawLines[i].match(/^([ \t]*)(?:async\s+)?def\s+(\w+)/);
    if (!m) continue;
    const indent = m[1].replace(/\t/g, '    ').length;
    let j = i + 1;
    for (; j < rawLines.length; j++) {
      const line = rawLines[j];
      if (line.trim() === '') continue;
      const cur = line.match(/^[ \t]*/)[0].replace(/\t/g, '    ').length;
      if (cur <= indent) break;
    }
    const len = j - i;
    if (len > best.lines) best = { name: m[2], lines: len, at: i + 1 };
  }
  return best;
}

const DECL_TYPE = /^\s*(export\s+)?(declare\s+)?(interface|type|enum|struct|record)\b/;
const DECL_ANY =
  /^\s*(export\s+|public\s+|pub\s+|private\s+)?(default\s+)?(abstract\s+)?(async\s+)?(class|interface|type|enum|struct|record|function|const|let|var|def|fn|func|impl|trait)\b/;

/** Flat `case`/route/key arms that never nest — the signature of a table written as code. */
function flatArmCount(maskedLines) {
  let n = 0;
  for (const line of maskedLines) {
    if (/^\s*case\s+/.test(line)) n++;
    else if (/^\s*['"`\w[.@$/-]+\s*:\s*[[{(]/.test(line)) n++;
  }
  return n;
}

/**
 * A deeply nested object/schema literal is DATA, not logic — brace depth alone would score it as
 * the worst file in the folder. Separate the two by how much control flow is actually present.
 */
const CONTROL_KEYWORD = /\b(if|for|while|catch|throw|await|return)\b/;
const DATA_LINE = /^\s*(['"`]?[\w$.-]+['"`]?)\s*:\s*[^=]/;

function densities(maskedLines, loc) {
  let control = 0;
  let data = 0;
  for (const line of maskedLines) {
    if (CONTROL_KEYWORD.test(line)) control++;
    if (DATA_LINE.test(line)) data++;
  }
  return { control: control / Math.max(1, loc), data: data / Math.max(1, loc) };
}

function classifyShape(file, text, m) {
  if (GENERATED_DIR.test(file) || GENERATED_HEADER.test(text.slice(0, 2000))) return 'generated';
  if (m.loc < 60) return m.maxDepth <= 2 ? 'types' : 'logic';

  const typeDecls = m.typeDecls;
  const allDecls = Math.max(1, m.allDecls);
  if (m.longestFn.lines <= 12 && typeDecls / allDecls >= 0.5) return 'types';
  if (m.maxDepth <= 2 && m.longestFn.lines <= 20) return 'types';

  // Control-flow density is what actually separates a god file from a big table. Measured across
  // this repo: true god services sit at 0.15-0.25; schema literals and command trees at 0.05-0.09.

  // Data expressed as code: schema/config literals nest deeply but branch on nothing.
  if (m.density.data >= 0.35 && m.density.control <= 0.1) return 'registry';

  // Flat structure with almost no branching — a route table, command tree or dispatch map,
  // even when the whole thing is wrapped in one enormous builder function.
  if (m.maxDepth <= 4 && m.density.control <= 0.08) return 'registry';

  const flatRatio = m.flatArms / m.loc;
  if (m.maxDepth <= 4 && m.longestFn.lines <= 90 && (flatRatio >= 0.12 || m.exports / m.loc >= 0.06))
    return 'registry';

  return 'logic';
}

function hasAdjacentTest(file) {
  const ext = extname(file);
  const base = basename(file, ext);
  const dir = dirname(file);
  const candidates = [
    join(dir, `${base}.spec${ext}`),
    join(dir, `${base}.test${ext}`),
    join(dir, '__tests__', `${base}.spec${ext}`),
    join(dir, '__tests__', `${base}.test${ext}`),
    join(dir, `test_${base}${ext}`),
    join(dir, 'tests', `test_${base}${ext}`),
  ];
  return candidates.some((c) => existsSync(c));
}

function analyzeFile(file, text) {
  const ext = extname(file);
  const rawLines = text.split(/\r?\n/);
  const masked = maskCode(text);
  const maskedLines = masked.split(/\r?\n/);
  const indentLang = INDENT_EXT.has(ext);

  const m = {
    total: rawLines.length,
    loc: codeLines(rawLines, maskedLines),
    exports: (masked.match(/^\s*(export|pub |public |module\.exports)/gm) || []).length,
    maxDepth: indentLang ? maxIndentDepth(rawLines) : maxBraceDepth(maskedLines),
    longestFn: indentLang ? longestIndentFunction(rawLines) : longestBraceFunction(maskedLines),
    typeDecls: (masked.match(new RegExp(DECL_TYPE.source, 'gm')) || []).length,
    allDecls: (masked.match(new RegExp(DECL_ANY.source, 'gm')) || []).length,
    flatArms: flatArmCount(maskedLines),
  };
  m.density = densities(maskedLines, m.loc);
  m.shape = classifyShape(file, text, m);
  return m;
}

let files;
try {
  files = statSync(root).isDirectory() ? walk(root) : [root];
} catch {
  console.error(`Path not found: ${root}`);
  process.exit(1);
}

const results = files
  .map((f) => ({
    file: relative(root, f) || basename(f),
    test: TEST_FILE.test(f),
    hasTest: TEST_FILE.test(f) ? null : hasAdjacentTest(f),
    ...analyzeFile(f, readFileSync(f, 'utf8')),
  }))
  .sort((a, b) => b.loc - a.loc);

const tests = results.filter((r) => r.test);
const src = results.filter((r) => !r.test && r.shape !== 'generated');
const generated = results.filter((r) => !r.test && r.shape === 'generated');

const oversized = src.filter((r) => r.loc > maxLoc);
const review = oversized.filter((r) => r.shape === 'logic');
const flatLarge = oversized.filter((r) => r.shape !== 'logic');
const longFns = src.filter((r) => r.longestFn.lines > LONG_FN && r.shape === 'logic');
const untestedLarge = src.filter((r) => !r.hasTest && r.loc > 250);
const totalLoc = src.reduce((s, r) => s + r.loc, 0);
const testLoc = tests.reduce((s, r) => s + r.loc, 0);

if (asJson) {
  console.log(
    JSON.stringify(
      {
        root,
        maxLoc,
        totalLoc,
        testLoc,
        fileCount: src.length,
        generatedCount: generated.length,
        review,
        flatLarge,
        longFns,
        untestedLarge,
        files: results,
      },
      null,
      2
    )
  );
  process.exit(0);
}

const pad = (s, n) => String(s).padEnd(n);
console.log(`\n  Target: ${root}`);
console.log(
  `  Source files: ${src.length}   Code lines: ${totalLoc}   Test files: ${tests.length} (${testLoc} lines)` +
    (generated.length ? `   Generated (excluded): ${generated.length}` : '')
);
console.log(`  Size threshold: ${maxLoc}    (size locates; SHAPE decides)\n`);
console.log(
  `  ${pad('LOC', 6)}${pad('LINES', 7)}${pad('EXP', 5)}${pad('DEPTH', 6)}${pad('SHAPE', 10)}${pad('TEST', 6)}${pad('LONGEST FN', 22)}FILE`
);
console.log('  ' + '-'.repeat(100));
for (const r of src.slice(0, topN)) {
  const flag = r.loc > maxLoc && r.shape === 'logic' ? '!' : ' ';
  const fn = r.longestFn.lines ? `${r.longestFn.name}(${r.longestFn.lines})` : '-';
  console.log(
    `${flag} ${pad(r.loc, 6)}${pad(r.total, 7)}${pad(r.exports, 5)}${pad(r.maxDepth, 6)}${pad(r.shape, 10)}${pad(r.hasTest ? 'yes' : 'NO', 6)}${pad(fn, 22)}${r.file}`
  );
}
if (src.length > topN) console.log(`  ... ${src.length - topN} more`);

console.log('');
if (review.length) {
  console.log(`  REVIEW FIRST — large 'logic' files (> ${maxLoc} LOC), split by responsibility:`);
  for (const r of review)
    console.log(`    - ${r.file}  (${r.loc} LOC, depth ${r.maxDepth}, test: ${r.hasTest ? 'yes' : 'NO'})`);
} else {
  console.log(`  No 'logic' files over ${maxLoc} LOC.`);
}
if (flatLarge.length) {
  console.log(`\n  LARGE BUT FLAT — verify before flagging; a big table is not a god file:`);
  for (const r of flatLarge) console.log(`    - ${r.file}  (${r.loc} LOC, shape ${r.shape}, depth ${r.maxDepth})`);
}
if (untestedLarge.length) {
  console.log(`\n  NO ADJACENT TEST (> 250 LOC) — characterize before moving any of these:`);
  for (const r of untestedLarge) console.log(`    - ${r.file}  (${r.loc} LOC, shape ${r.shape})`);
}
if (longFns.length) {
  console.log(`\n  LONG FUNCTIONS (> ${LONG_FN} lines) — candidates to break up:`);
  for (const r of longFns)
    console.log(`    - ${r.file}:${r.longestFn.at} :: ${r.longestFn.name} (${r.longestFn.lines} lines)`);
}
if (generated.length) {
  console.log(`\n  GENERATED (excluded — fix the generator, never the output):`);
  for (const r of generated.slice(0, 10)) console.log(`    - ${r.file}  (${r.loc} LOC)`);
  if (generated.length > 10) console.log(`    ... ${generated.length - 10} more`);
}
console.log('');
