/**
 * PendingSessionManagerService - Pending Session Resolution Management
 *
 * Manages pending session ID resolutions with immediate cleanup.
 * Eliminates shared mutable state between SessionLoaderService and ConversationService.
 *
 * Extracted from ChatStore refactoring (TASK_2025_054) - Batch 1
 * Simplified in TASK_2025_068 - Batch 5 (removed timeout complexity)
 *
 * Architecture:
 * - Single Responsibility: Manage pending session resolutions Map
 * - Encapsulation: Map is private (no external mutation)
 * - Immediate cleanup: No timeouts, cleanup on resolution or failure
 * - Simple interface: add(), remove(), get(), has()
 */

import { Injectable } from '@angular/core';

/**
 * Manages pending session ID resolutions with immediate cleanup
 *
 * Use case:
 * When a new conversation starts, we generate a placeholder session ID.
 * The backend will eventually respond with a real Claude CLI session UUID.
 * This service tracks which tab initiated each pending session so we can
 * resolve the correct tab when the backend responds.
 *
 * Cleanup handling:
 * Resolutions are removed immediately when resolved or on RPC failure.
 * The atomic TabManager.resolveSessionId ensures proper state updates.
 */
@Injectable({ providedIn: 'root' })
export class PendingSessionManagerService {
  // ============================================================================
  // PRIVATE STATE
  // ============================================================================

  /**
   * Map of pending session resolutions: placeholder sessionId -> tabId
   * Tracks which tab initiated each pending session
   */
  private readonly resolutions = new Map<string, string>();

  // ============================================================================
  // PUBLIC API
  // ============================================================================

  /**
   * Add pending session resolution
   * Uses immediate cleanup pattern - removed on resolution or RPC failure
   *
   * @param sessionId - Placeholder session ID (generated by frontend)
   * @param tabId - Tab ID that initiated this conversation
   *
   * @example
   * // When starting new conversation:
   * const sessionId = generateId();
   * pendingSessionManager.add(sessionId, activeTabId);
   * await claudeRpc.call('chat:start', { sessionId, ... });
   */
  add(sessionId: string, tabId: string): void {
    // Store resolution mapping (no timeout)
    this.resolutions.set(sessionId, tabId);

    console.log('[PendingSessionManager] Added pending resolution:', {
      sessionId,
      tabId,
    });
  }

  /**
   * Remove pending resolution (on success or failure)
   * Immediate cleanup - no timeout to clear
   *
   * @param sessionId - Session ID to remove
   * @returns Tab ID if found, undefined otherwise
   *
   * @example
   * // When session ID is resolved:
   * const tabId = pendingSessionManager.remove(sessionId);
   * if (tabId) {
   *   // TabManager handles atomic resolution
   *   tabManager.resolveSessionId(placeholderId, realSessionId);
   * }
   *
   * @example
   * // When RPC fails:
   * try {
   *   await claudeRpc.call('chat:start', ...);
   * } catch (error) {
   *   pendingSessionManager.remove(sessionId); // Immediate cleanup
   *   throw error;
   * }
   */
  remove(sessionId: string): string | undefined {
    const tabId = this.resolutions.get(sessionId);

    // Remove from resolutions map (immediate cleanup)
    this.resolutions.delete(sessionId);

    if (tabId) {
      console.log('[PendingSessionManager] Removed pending resolution:', {
        sessionId,
        tabId,
      });
    }

    return tabId;
  }

  /**
   * Get tab ID for pending session
   *
   * @param sessionId - Session ID to lookup
   * @returns Tab ID if found, undefined otherwise
   *
   * @example
   * // When session:id-resolved event arrives:
   * const tabId = pendingSessionManager.get(placeholderSessionId);
   * if (tabId) {
   *   const tab = tabManager.findTab(tabId);
   *   // Resolve session ID for this specific tab
   * }
   */
  get(sessionId: string): string | undefined {
    return this.resolutions.get(sessionId);
  }

  /**
   * Check if session has pending resolution
   *
   * @param sessionId - Session ID to check
   * @returns true if pending, false otherwise
   *
   * @example
   * if (pendingSessionManager.has(sessionId)) {
   *   console.log('Session is still pending resolution');
   * }
   */
  has(sessionId: string): boolean {
    return this.resolutions.has(sessionId);
  }
}
