/**
 * PendingSessionManagerService - Pending Session Resolution Management
 *
 * Manages pending session ID resolutions with timeout-based auto-cleanup.
 * Eliminates shared mutable state between SessionLoaderService and ConversationService.
 *
 * Extracted from ChatStore refactoring (TASK_2025_054) - Batch 1
 *
 * Architecture:
 * - Single Responsibility: Manage pending session resolutions Map
 * - Encapsulation: Map and timeouts are private (no external mutation)
 * - Auto-cleanup: 60-second timeout prevents memory leaks
 * - Simple interface: add(), remove(), get(), has()
 */

import { Injectable } from '@angular/core';

/**
 * Manages pending session ID resolutions with timeout-based cleanup
 *
 * Use case:
 * When a new conversation starts, we generate a placeholder session ID.
 * The backend will eventually respond with a real Claude CLI session UUID.
 * This service tracks which tab initiated each pending session so we can
 * resolve the correct tab when the backend responds.
 *
 * Timeout handling:
 * If a session is never resolved (RPC failure, network issues), it will
 * auto-cleanup after 60 seconds to prevent memory leaks.
 */
@Injectable({ providedIn: 'root' })
export class PendingSessionManagerService {
  // ============================================================================
  // PRIVATE STATE
  // ============================================================================

  /**
   * Map of pending session resolutions: placeholder sessionId -> tabId
   * Tracks which tab initiated each pending session
   */
  private readonly resolutions = new Map<string, string>();

  /**
   * Map of timeout IDs: sessionId -> timeout ID
   * Used to cleanup timeouts when sessions are resolved early
   * Using ReturnType<typeof setTimeout> for cross-environment compatibility
   */
  private readonly timeouts = new Map<
    string,
    ReturnType<typeof setTimeout>
  >();

  /**
   * Timeout duration in milliseconds (60 seconds)
   * Sufficient for typical RPC roundtrip, even on slow networks
   */
  private static readonly TIMEOUT_MS = 60000;

  // ============================================================================
  // PUBLIC API
  // ============================================================================

  /**
   * Add pending session resolution
   * Creates a timeout that will auto-cleanup after 60 seconds if not resolved
   *
   * @param sessionId - Placeholder session ID (generated by frontend)
   * @param tabId - Tab ID that initiated this conversation
   *
   * @example
   * // When starting new conversation:
   * const sessionId = generateId();
   * pendingSessionManager.add(sessionId, activeTabId);
   * await claudeRpc.call('chat:start', { sessionId, ... });
   */
  add(sessionId: string, tabId: string): void {
    // Store resolution mapping
    this.resolutions.set(sessionId, tabId);

    // Create auto-cleanup timeout
    const timeout = setTimeout(() => {
      console.warn(
        `[PendingSessionManager] Timeout for session: ${sessionId} (tab: ${tabId})`
      );
      this.remove(sessionId);
    }, PendingSessionManagerService.TIMEOUT_MS);

    // Store timeout for later cleanup
    this.timeouts.set(sessionId, timeout);

    console.log('[PendingSessionManager] Added pending resolution:', {
      sessionId,
      tabId,
      timeoutMs: PendingSessionManagerService.TIMEOUT_MS,
    });
  }

  /**
   * Remove pending resolution (on success or failure)
   * Clears associated timeout to prevent orphaned timers
   *
   * @param sessionId - Session ID to remove
   * @returns Tab ID if found, undefined otherwise
   *
   * @example
   * // When session ID is resolved:
   * const tabId = pendingSessionManager.remove(sessionId);
   * if (tabId) {
   *   // Update the correct tab
   *   tabManager.resolveSessionId(tabId, realSessionId);
   * }
   *
   * @example
   * // When RPC fails:
   * try {
   *   await claudeRpc.call('chat:start', ...);
   * } catch (error) {
   *   pendingSessionManager.remove(sessionId); // Cleanup
   *   throw error;
   * }
   */
  remove(sessionId: string): string | undefined {
    const tabId = this.resolutions.get(sessionId);

    // Remove from resolutions map
    this.resolutions.delete(sessionId);

    // Clear timeout to prevent orphaned timer
    const timeout = this.timeouts.get(sessionId);
    if (timeout) {
      clearTimeout(timeout);
      this.timeouts.delete(sessionId);
    }

    if (tabId) {
      console.log('[PendingSessionManager] Removed pending resolution:', {
        sessionId,
        tabId,
      });
    }

    return tabId;
  }

  /**
   * Get tab ID for pending session
   *
   * @param sessionId - Session ID to lookup
   * @returns Tab ID if found, undefined otherwise
   *
   * @example
   * // When session:id-resolved event arrives:
   * const tabId = pendingSessionManager.get(placeholderSessionId);
   * if (tabId) {
   *   const tab = tabManager.findTab(tabId);
   *   // Resolve session ID for this specific tab
   * }
   */
  get(sessionId: string): string | undefined {
    return this.resolutions.get(sessionId);
  }

  /**
   * Check if session has pending resolution
   *
   * @param sessionId - Session ID to check
   * @returns true if pending, false otherwise
   *
   * @example
   * if (pendingSessionManager.has(sessionId)) {
   *   console.log('Session is still pending resolution');
   * }
   */
  has(sessionId: string): boolean {
    return this.resolutions.has(sessionId);
  }
}
